opensearch-project/opensearch-benchmark

- osbenchmark/builder/cluster_builder.py
- osbenchmark/builder/downloaders/downloader.py
- osbenchmark/builder/executors/executor.py
- osbenchmark/builder/installers/installer.py
- osbenchmark/builder/launchers/launcher.py
- osbenchmark/builder/provisioners/provisioner.py
Creates the interfaces for the components of the builder system expansion. More details about these components can be found in #113 
closes #131 
> Create provisioning system interfaces

- docs/api/client-options.md
- docs/api/execute-test.md
- docs/api/index.md
- docs/api/kill-running-process.md
- docs/api/pipeline.md
- docs/api/target-hosts.md
- docs/api/test-mode.md
- docs/api/workload.md
- docs/get-started.md
- docs/user-guides/create-pipeline.md
Signed-off-by: Naarcha-AWS <naarcha@amazon.com>
---
> Add initial doc structure

- .ci/build.sh
- .github/workflows/manual-integ.yml
- Makefile
- it/distribution_test.py
- it/download_test.py
Fix integration test workflow
---
> Fix integration test workflow

- .github/workflows/dockerfile-lint.yml
- docker/Dockerfile
Add back slash to schema label and add dockerfile-lint.yml
---
> Dockerfile bug fix

- docker/Dockerfile
Use correct quotes in the dockerfile
---
> Use correct quotes in the dockerfile

- docker/README.md
- jenkins/release.JenkinsFile
This PR adds OSB to Jenkins Workflow that publishes to Dockerhub staging. Also, updated Docker README to be in line with the Dockerhub repository overview. Included an issue statement regarding 0.2.0 version of OSB. 
#255 
---
> Onboard OSB to Jenkins Workflow to publish to Dockerhub

- docker/Dockerfile
Adding build args and removing hardcoded values in Dockerfile
Related to #262 
---
> Update Dockerfile with Build Args

- osbenchmark/__init__.py
> Updated forum link to the correct URL

- setup.py
> Revert topic classifier

- docker/Dockerfile
Fix docker file for 0.4.1 release
---
> Fix docker file for 0.4.1 release

- docker/README.md
Updated docker README for the 0.4.1 release.
---
> Docker README update for 0.4.1

- README.md
Trivial update to docs link to point to the latest.
n/a
---
> Point docs link to the latest

- DEVELOPER_GUIDE.md
Adds section to suggest users to debug OSB with developer mode
N/A
---
> Add Debugging Section to Developer Guide

- DEVELOPER_GUIDE.md
> Fix DEVELOPER_GUIDE.md

- RELEASE_GUIDE.md
After 1.3.1 patch release, updating RELEASE_GUIDE.md to add clarity.
---
> Revise RELEASE_GUIDE.md for better practices and clarity on patch releases

- README.md
Logo isn't showing up but updated link in README and it does now.
---
> Update README to show actual image logo

- osbenchmark/utils/io.py
- osbenchmark/workload/loader.py
- tests/workload/loader_test.py
Update to #542, download offset files only when not already present.
Unit and integ tests.
---
> Download pre-generated offset files only when needed

- osbenchmark/metrics.py
- tests/metrics_test.py
The in-memory metrics store has the potential to run out of memory, especially when ingesting large data corpora.  This can result in unpleasant behavior and inaccurate performance metrics.  This change adds warnings so that the user is made aware of the situation and can restart the run after switching to an external data store.
https://github.com/opensearch-project/opensearch-benchmark-workloads/issues/296
Multiple tests with the 1 TB _big5_ corpus.  Ran unit and integ tests.  Will open a separate issue against _systemd_ relating to the network stack going down in OOM situations.
---
For more information on following Developer Certificate of Origin and signing off your …
> Check that the in-memory metrics store does not run out of memory

- README.md
Quick fix on README. Tested in personal fork
---
> Fix bracket in Chat on Forum Badge

- DEVELOPER_GUIDE.md
> Provide instructions on how to run integration tests locally

- osbenchmark/workload/loader.py
- tests/workload/loader_test.py
Remove downloaded files after corpus has been generated.
Unit and integ tests.
---
> Minor updates for multi-part downloads

- .github/CODEOWNERS
- MAINTAINERS.md
- In interest of other priorities, I would like to remove myself from maintainer list
NA
NA
NA
---
> update maintainers list

- .github/workflows/docker-push-release.yml
Migrate QEMU bug workaround to the DockerHub build.
---
> Workaround for the QEMU bug for the DockerHub build

- setup.py
> Change Topic name used by PyPI back to Benchmark from OSB.

- .github/workflows/docker-build.yml
- .github/workflows/docker-push-release.yml
Updated the Docker workflows to use the current version of buildx
#735 
---
> Updated the Docker workflows to use the current version of buildx

- setup.py
Backport of https://github.com/opensearch-project/opensearch-benchmark/pull/807
---
> Bump twine version

- setup.py
> Unblock release

- .github/workflows/publish-release.yml
- osbenchmark/benchmark.py
- osbenchmark/utils/io.py
- osbenchmark/worker_coordinator/runner.py
- osbenchmark/worker_coordinator/worker_coordinator.py
- tests/worker_coordinator/worker_coordinator_test.py
Need to rebase 3 latest commits onto OSB's 1.13 branch
---
> Rebase latest commits to 1.13 to kickstart release

- osbenchmark/worker_coordinator/worker_coordinator.py
Previous `scale_up()` method in the FeedbackActor did not achieve an even distribution of clients across workers:
```
2025-05-15 19:27:52,11 ActorAddr-(T|:59543)/PID:29215 osbenchmark.worker_coordinator.worker_coordinator INFO Unpaused client 0 on worker 0
2025-05-15 19:27:52,16 ActorAddr-(T|:59543)/PID:29215 osbenchmark.worker_coordinator.worker_coordinator INFO Unpaused client 1 on worker 0
2025-05-15 19:27:52,20 ActorAddr-(T|:59543)/PID:29215 osbenchmark.worker_coordinator.worker_coordinator INFO Unpaused client 2 on worker 0
2025-05-15 19:27:52,24 ActorAddr-(T|:59543)/PID:29215 osbenchmark.worker_coordinator.worker_coordinator INFO Unpaused client 3 on worker 0
2025-05-15 19:27:52,30 ActorAddr-(T|:59543)/PID:29215 osbenchmark.worker_coordinator.worker_coordinator INFO Unpaused client …
```
> change feedback actor's scale up method to use random sampling

- osbenchmark/workload/workload.py
Block Scroll query for OSS as it is not supported. 
---
> Block Scroll query for OSS as it is not supported

- osbenchmark/worker_coordinator/worker_coordinator.py
- tests/worker_coordinator/worker_coordinator_test.py
Backports this approved PR to 2.0.0-alpha
---
> Updates to Redline Testing (#849)

- osbenchmark/benchmark.py
- osbenchmark/client.py
- osbenchmark/cloud_provider/__init__.py
- osbenchmark/cloud_provider/cloud_provider.py
- osbenchmark/cloud_provider/factory.py
- osbenchmark/cloud_provider/vendors/__init__.py
- osbenchmark/cloud_provider/vendors/aws.py
- osbenchmark/exceptions.py
- osbenchmark/metrics.py
- osbenchmark/resources/example-basic-mappings.json
- osbenchmark/resources/example-complex-mappings.json
- osbenchmark/resources/sdg-config.yml
- osbenchmark/synthetic_data_generator/__init__.py
- osbenchmark/synthetic_data_generator/custom_synthetic_data_generator.py
- osbenchmark/synthetic_data_generator/helpers.py
- osbenchmark/synthetic_data_generator/input_processor.py
- osbenchmark/synthetic_data_generator/mapping_synthetic_data_generator.py
- osbenchmark/synthetic_data_generator/synthetic_data_generator.py
- osbenchmark/synthetic_data_generator/types.py
- osbenchmark/worker_coordinator/worker_coordinator.py
- setup.py
- tests/synthetic_data_generator/custom_synthetic_data_generator_test.py
- tests/synthetic_data_generator/mapping_synthetic_data_generator_test.py
- tests/worker_coordinator/worker_coordinator_test.py
This PR keeps `2.0-develop` up to date with `main`
#865 
---
> Rebase main changes onto 2.0-develop

- setup.py
> Update classifier to correct naming
