osbenchmark/builder/provisioner.py
osbenchmark/tracker/tracker.py
osbenchmark/workload/loader.py

Signed-off-by: Achit Ojha <achiojha@amazon.com>
Changes to jinja environments instantiation to have autoescape enabled by default for html content.
#92 
- [X ] All unit and integration tests pass

Enable autoescaping in Jinja2 of HTML and XML content, to mitigate XSS attacks

---

NOTICE
README.md

Bump OpenSearch copyright to 2022
- https://github.com/opensearch-project/opensearch-benchmark/issues/94

Change OpenSearch copyrights to 2022

---

osbenchmark/telemetry.py
samples/ccr/docker-compose-metricstore.yml
samples/ccr/docker-compose.yml
samples/ccr/start.sh
samples/ccr/stop.sh
tests/telemetry_test.py
tests/worker_coordinator/worker_coordinator_test.py

Signed-off-by: Ankit Kala <ankikala@amazon.com>
This PR replaces the CCR telemetry logic used by xpack Elasticsearch with OpenSearch cross cluster replication plugin.
[88](https://github.com/opensearch-project/opensearch-benchmark/issues/88)
[1428](https://github.com/opensearch-project/opensearch-build/issues/1428)

Updating CCR telemetry device for OpenSearch.

---

osbenchmark/builder/provisioner.py
osbenchmark/tracker/tracker.py
osbenchmark/workload/loader.py

Directly imports jinja2's select_autoescape method and replaces all references to jinja2.select_autoescape with select_autoescape
- [x ] New functionality includes testing
- [ x] All unit tests pass
- [ x] Commits are signed per the DCO using --signoff 

Directly import jinja2.select_autoescape

---

setup.py

Selects a Jinja compatible version of MarkupSafe to install when `pip` installing OpenSearch Benchmark. This fix can be tested by runninng `pip3 install git+https://github.com/opensearch-project/opensearch-benchmark.git@bad3eff70a9f732ae3f2c7e7d4ac0e4f68d29c1e`
https://github.com/opensearch-project/opensearch-benchmark/issues/111

Set MarkupSafe version to 2.0.1

---

it/list_test.py

Updating the commit hash in the integration test `test_list_workloads` to a hash after `challenges` was renamed to `test_procedures` in the workloads repo. Now the test passes:
```
it/list_test.py::test_list_workloads[in-memory-it]
/ /_/ / /_/ /  __/ / / /__/ /  __/ /_/ / /  / /__/ / / /  / /_/ /  __/ / / / /__/ / / / / / / / / /_/ / /  / ,<
\____/ .___/\___/_/ /_/____/\___/\__,_/_/   \___/_/ /_/  /_____/\___/_/ /_/\___/_/ /_/_/ /_/ /_/\__,_/_/  /_/|_|
/_/ …
```

Update workload load repo commit hash to working revision in test_list_workloads IT

---

it/resources/benchmark-os-it.ini

The integration test metrics store is being marked as secure but not created as such. This causes an SSL error when trying to connect using https. This PR reverts the secure setting, allowing the integration tests to connect to the metrics store:
```
it/distribution_test.py::test_tar_distributions[os-it]
/ /_/ / /_/ /  __/ / / /__/ /  __/ /_/ / /  / /__/ / / /  / /_/ /  __/ / / / /__/ / / / / / / / / /_/ / /  / ,<
\____/ .___/\___/_/ /_/____/\___/\__,_/_/ …
```

Reverting OpenSearch metrics store to be insecure in the integration tests

---

osbenchmark/resources/docker-compose.yml.j2
tests/builder/provisioner_test.py

This PR fixes the Docker integration test by editing the docker-compose.yml.j2 file to remove the `cluster.initial_master_nodes` setting and adding a health check. More details about why it was failing before can be found in #117 
```
it/distribution_test.py::test_docker_distribution[os-it]
/ /_/ / /_/ /  __/ / / /__/ /  __/ /_/ / /  / /__/ / / /  / /_/ /  __/ / / / /__/ / / / / / / / / /_/ / /  / ,<
\____/ .___/\___/_/ /_/____/\___/\__,_/_/   \___/_/ /_/ …
```

Removing cluster.initial_master_nodes and adding healthcheck to docker-compose.yml.j2

---

it/__init__.py

Assertions can be defined in OSB workload operations to ensure the operation's result is as expected. [Example](https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/main/http_logs/operations/default.json#L76-L82). Only `http_logs` has these assertions presently:
```
grep -rnw "assertions" *
http_logs/operations/default.json:76:      "assertions": [
http_logs/operations/default.json:99:      "assertions": [
http_logs/operations/default.json:133:      "assertions": [
http_logs/operations/default.json:167:      "assertions": [
```
Since the integration tests run in `--test-mode`, the assertions fail since the entire corpus is not ingested. This PR removes the `--enable-assertions` flag when integration tests are running
Signed-off-by: Chase Engelbrecht …

Removing --enable-assertions flag from integration test runs

---

.ci/build.sh
.github/workflows/manual-integ.yml
tox.ini

This PR fills in the gaps to get the integration tests running on Github Actions. This required installing JDK16, pulling the squid container, and updating the `BENCHMARK_HOME` environment variable.
The Github Actions integration tests run in 2 parallel streams, one for python 3.8 and one for python 3.9. The unit tests have been removed from the tox.ini commands since they are run in a separate Github Actions workflow.
Potential further enhancements:
1. The current containers use Ubuntu, we may want to add a MacOS iteration as well
2. Certain integration tests [pick randomly](https://github.com/opensearch-project/opensearch-benchmark/blob/main/it/distribution_test.py#L28) between using an in-memory or OpenSearch metrics store. This can lead to different results on different runs, even …

Small fixes to get the integration tests working on Github Actions, adding the tests to pull_requests

---

opensearch-benchmark-provisionconfigs/1.0/plugins/v1/repository_azure/plugin.py
opensearch-benchmark-provisionconfigs/1.0/plugins/v1/repository_gcs/plugin.py
opensearch-benchmark-provisionconfigs/1.0/plugins/v1/repository_s3/plugin.py
opensearch-benchmark-provisionconfigs/main/plugins/v1/repository_azure/plugin.py
opensearch-benchmark-provisionconfigs/main/plugins/v1/repository_gcs/plugin.py
opensearch-benchmark-provisionconfigs/main/plugins/v1/repository_s3/plugin.py
osbenchmark/async_connection.py
osbenchmark/client.py
osbenchmark/metrics.py
osbenchmark/telemetry.py
osbenchmark/tracker/corpus.py
osbenchmark/tracker/tracker.py
osbenchmark/utils/opts.py
osbenchmark/worker_coordinator/runner.py
osbenchmark/worker_coordinator/worker_coordinator.py
setup.py
tests/builder/launcher_test.py
tests/client_test.py
tests/metrics_test.py
tests/telemetry_test.py
tests/tracker/corpus_test.py
tests/tracker/index_test.py
tests/worker_coordinator/runner_test.py
tests/worker_coordinator/worker_coordinator_test.py

Signed-off-by: Achit Ojha <achiojha@amazon.com>
OpenSearch Benchmark currently uses [Elasticsearch client](https://pypi.org/project/elasticsearch/). This goal of this issue is to replace the Elaticsearch client with the [OpenSearch Python client](https://pypi.org/project/opensearch-py/)
#63 
- [X ] New functionality includes testing
- [X ] All unit and integration tests pass
- [X ] Commits are signed per the DCO using --signoff 

Migrate from elasticsearch client to opensearch python client

---

osbenchmark/builder/models/cluster_flavors.py
osbenchmark/builder/models/cluster_infra_providers.py
osbenchmark/builder/models/flavors.py
osbenchmark/builder/models/providers.py
osbenchmark/builder/provision_config.py

Adds the new Provider and Flavor models for the build system expansion.
#132 

Add Provider and Flavor enums, populate their default values in ProvisionConfigInstance

---

osbenchmark/builder/launchers/exception_handling_launcher.py
osbenchmark/builder/launchers/local_process_launcher.py
tests/builder/launchers/local_process_launcher_test.py

Migrates the ProcessLauncher to a LocalProcessLauncher. Adds an ExceptionHandlingLauncher to decorate the Launcher implementations with exception handling.
I initially tried to generalize the LocalProcessLauncher to use shell commands instead of helpers such as `io` or `os` modules. This would have allowed the implementation to be used by non-local providers. However, the telemetry devices and `java_resolver` are tightly coupled to evaluating the local machine as well and would have required significant refactoring.
Rather than going this route, I decided that a separate implementation for ExternalProcessLauncher could be created to handle the generalized flow of this class without coupling the logic to the local machine. This seems to the be quickest and cleanest path forwards. If there …

Create LocalProcessLauncher and ExceptionHandlingLauncher

---

osbenchmark/builder/models/cluster.py
osbenchmark/builder/models/host.py
osbenchmark/builder/models/node.py

Adds the models to represent a cluster constructed by the builder. The models will be populated as the builder system progresses through creating a cluster.
Cluster and Host are new models, Node is a combination of the existing [Node](https://github.com/opensearch-project/opensearch-benchmark/blob/main/osbenchmark/builder/cluster.py#L26) and [NodeConfiguration](https://github.com/opensearch-project/opensearch-benchmark/blob/main/osbenchmark/builder/provisioner.py#L66) models to serve as a singular representation of a node.
#132  …

Create Cluster, Host, and Node models

---

osbenchmark/builder/utils/java_home_resolver.py
tests/builder/utils/java_home_resolver_test.py

Migrates the [java_resolver](https://github.com/opensearch-project/opensearch-benchmark/blob/main/osbenchmark/builder/java_resolver.py) functionality to a `JavaHomeResolver` class that utilizes an executor. This allows the builder subcomponents to use the `JavaHomeResolver` regardless of the cluster infrastructure provider.
#134 

Migrate java_resolver file to JavaHomeResolver class with executor

---

osbenchmark/builder/downloaders/repositories/opensearch_distribution_repository_provider.py
osbenchmark/builder/downloaders/repositories/plugin_distribution_repository_provider.py
osbenchmark/builder/downloaders/repositories/repository_url_provider.py
osbenchmark/builder/installers/docker_installer.py
osbenchmark/builder/utils/config_applier.py
osbenchmark/builder/utils/template_renderer.py
tests/builder/downloaders/repositories/opensearch_distribution_repository_provider_test.py
tests/builder/downloaders/repositories/plugin_distribution_repository_provider_test.py
tests/builder/downloaders/repositories/repository_url_provider_test.py
tests/builder/utils/config_applier_test.py
tests/builder/utils/template_renderer_test.py

Added the following helper classes: `OpenSearchDistributionRepositoryProvider`, `PluginDistributionRepositoryProvider`, and `RepositoryUrlProvider`. These classes will be used by the Downloaders for fetching the distributions from a given repository.
Additionally, the TemplateRenderer was refactored to have 2 methods: `render_template_file` and `render_template_string`.
#134 

Create Repository helper classes to be consumed by the Downloaders

---

osbenchmark/builder/installers/exception_handling_installer.py
osbenchmark/exceptions.py

Adds ExceptionHandlingInstaller as decorator for top-level exception handling
#134 

Implement ExceptionHandlingInstaller

---

osbenchmark/builder/downloaders/opensearch_distribution_downloader.py
osbenchmark/builder/downloaders/plugin_distribution_downloader.py
tests/builder/downloaders/opensearch_distribution_downloader_test.py
tests/builder/downloaders/repositories/plugin_distribution_downloader_test.py

Migrates the Distribution based downloaders to conform to the new Downloader interface.
#134 

Migrate the OpenSearch and PluginDistributionDownloaders

---

osbenchmark/builder/downloaders/repositories/source_repository_provider.py
osbenchmark/builder/supplier.py
osbenchmark/builder/utils/git_manager.py
osbenchmark/builder/utils/path_manager.py
tests/builder/downloaders/repositories/source_repository_provider_test.py
tests/builder/utils/path_manager_test.py

Implements the `GitManager` and `SourceRepositoryProvider` helper classes. These classes will be consumed by the SourceDownloaders for fetching the code required to build OpenSearch and any plugins.
#134 

SourceRepositoryProvider Migration

---

osbenchmark/builder/downloaders/opensearch_distribution_downloader.py
osbenchmark/builder/downloaders/repositories/opensearch_distribution_repository_provider.py
osbenchmark/builder/downloaders/repositories/plugin_distribution_repository_provider.py
osbenchmark/builder/downloaders/repositories/repository_url_provider.py
osbenchmark/builder/executors/exception_handling_shell_executor.py
osbenchmark/builder/executors/local_shell_executor.py
osbenchmark/builder/installers/bare_installer.py
osbenchmark/builder/installers/docker_installer.py
osbenchmark/builder/installers/preparers/opensearch_preparer.py
osbenchmark/builder/launchers/docker_launcher.py
osbenchmark/builder/launchers/exception_handling_launcher.py
osbenchmark/builder/utils/config_applier.py
osbenchmark/builder/utils/java_home_resolver.py
osbenchmark/builder/utils/jdk_resolver.py
tests/builder/launchers/local_process_launcher_test.py
tests/builder/utils/path_manager_test.py

Follow up from #175 to prefer f-strings over .format()

Refactor to use f-strings instead of .format() in Builder system

---

osbenchmark/builder/models/bootstrap_phase.py
osbenchmark/builder/models/plugin_config_instance.py
osbenchmark/builder/models/provision_config_instance.py
osbenchmark/builder/models/provision_config_instance_descriptor.py
osbenchmark/builder/models/provision_config_instance_types.py

Migrates the existing models used for parsing a Provision and PluginConfigInstance to standalone dataclasses classes. The original models can be found in this class: https://github.com/opensearch-project/opensearch-benchmark/blob/main/osbenchmark/builder/provision_config.py
#132 

Migrate Provision and Plugin config parser models to standalone classes in the models module

---

osbenchmark/builder/downloaders/opensearch_distribution_downloader.py
osbenchmark/builder/downloaders/plugin_distribution_downloader.py
osbenchmark/builder/downloaders/repositories/opensearch_distribution_repository_provider.py
osbenchmark/builder/downloaders/repositories/plugin_distribution_repository_provider.py
osbenchmark/builder/downloaders/repositories/repository_url_provider.py
osbenchmark/builder/installers/preparers/opensearch_preparer.py
osbenchmark/builder/models/architecture_types.py
osbenchmark/builder/utils/artifact_variables_provider.py
osbenchmark/builder/utils/binary_keys.py
tests/builder/downloaders/opensearch_distribution_downloader_test.py
tests/builder/downloaders/plugin_distribution_downloader_test.py
tests/builder/downloaders/repositories/opensearch_distribution_repository_provider_test.py
tests/builder/downloaders/repositories/plugin_distribution_repository_provider_test.py
tests/builder/downloaders/repositories/repository_url_provider_test.py
tests/builder/installers/preparers/opensearch_preparer_test.py
tests/builder/utils/artifact_variables_provider_test.py

This PR creates the `ArtifactVariablesProvider` helper class which populates a dict with variables for version, arch, and osname. As part of breaking the logic for `ArtifactVariablesProvider` out of `RepositoryUrlProvider`, some minor refactoring was required. I took it a bit further and did the following:
* Remove instances of initialization in constructors for the distribution downloader classes, instead will use factory pattern
* Create new enum BinaryKeys to store the keys for the binaries map, replaced hard coded "opensearch" with reference to the appropriate binary key
For more information on following Developer Certificate of Origin and signing off your commits, please …

Refactors for using BinaryKey enum, factory pattern, and creating ArtifactVariablesProvider helper class

---

DEVELOPER_GUIDE.md

Signed-off-by: Travis Benedict <benedtra@amazon.com>
Add information to developer guide about how to deal with breaking changes. Also added some small updates about testing and DCO

Add information to developer guide about breaking changes

---

.github/CODEOWNERS
MAINTAINERS.md

Updated MAINTAINERS.md to reflect the active maintainers. Also created a CODEOWNERS in `.github` directory and added active maintainers there as suggested in the issue.
https://github.com/opensearch-project/opensearch-benchmark/issues/217
This doesn't affect testing.
---

Update MAINTAINERS.md and create CODEOWNERS to meet format for opensearch-project

---

DEVELOPER_GUIDE.md
PYTHON_SUPPORT_GUIDE.md

This PR adds documentation on how to add and test support for additional major and minor Python versions. 
N/A
- [N/A ] New functionality includes testing
No testing required as this is documentation related.
---

Add Documentation for Python Support Guide

---

docker/.dockerignore
docker/Dockerfile
docker/README.md

There was a bug introduced in the Dockerfile in the previous PR (#236). This was noticed after the previous PR was merged into main. Bug was discovered when I was making extra edits to Dockerfile. When I tried building the Dockerfile, I received the following error: 
```
failed to solve with frontend dockerfile.v0: failed to create LLB definition: Syntax error - can't find = in "VOLUME". Must be of the form: name=value
```
This PR fixes that bug and introduces a few more suggested edits to Dockerfile and README.md.
Changes:
- Remove extra `\` at the end of line 65 in Dockerfile
https://github.com/opensearch-project/opensearch-benchmark/blob/27cb82a40ecc6d04c125fbb155331722e18f8052/docker/Dockerfile#L65
- Simplify two `RUN` commands in Dockerfile with 
```
RUN find ./opensearch-benchmark …
```

Add Dockerfile Bug Fix and additional updates to Dockerfile / README.md

---

osbenchmark/utils/git.py
tests/utils/git_test.py

Integration tests and users using latest versions of `git (2.40.0)` experienced issues when using the `list` subcommand or OSB commands that relied on `workloads` repository. See #245 for more details. When invoking such commands, there would either be connection refused issues or `ValueError: substring not found` would appear. 
This PR applies the fix suggested in the issue #245. See the issue for more details. 
#245
- Tested it in an ubuntu environment (see https://github.com/opensearch-project/opensearch-benchmark/issues/245#issuecomment-1488907699)
- Tested in Integration Testing Environment in Github Actions
- Ran integration tests to confirm that fix resolved all failing integration tests. 
---
By submitting this pull request, I confirm that my …

Add fix for git.py to index from the right and reformat branches (#245)

---

osbenchmark/client.py
osbenchmark/telemetry.py
tests/telemetry_test.py

Users who are using OpenSearch versions greater than or less than 1.1.0 are still seeing the warn statement, which is misleading. This statement was originally intended for users running telemetry on ES versions 7.2.0 or less. This quick PR adds a condition to check if the distribution name is `opensearch` or `elasticsearch` in case OSB still wants to test ES versions <=7.10 (or prior to OpenSearch 1.0). 
Also, revised a logging statement from `ES` to `OpenSearch` when referring to the client. 
#243 
Tested OSB with and without changes in a fresh Ubuntu environment. Confirmed that the warn statement appears on the console and logs only when distribution name is `elasticsearch` and version is 7.2.0 or less.
---
By submitting this pull request, I confirm that my contribution is made under …

Add condition to check for distribution version when publishing warn statement

---

docker/Dockerfile
docker/README.md
osbenchmark/telemetry.py

Users on Dockerhub were having trouble running the command `docker run opensearchproject/opensearch-benchmark` in the README and Dockerhub repo's description. The commands exits with an exit status code of 0 because it doesn't run any entrypoint commands. This PR does the following:
- Adds entrypoint commands to Dockerfile
- Adds more information to the README to illuminate how to use the Docker image. 
- Adds the command that's been updated in the [Dockerhub repository](https://hub.docker.com/r/opensearchproject/opensearch-benchmark) so that there's consistency between the README and the Dockerhub repository overview tab.
Built image locally after updating Dockerfile and tested it with the following commands with Docker CLI. Tested on Docker Desktop to confirm consistency:
- `docker run …

Update Dockerfile and Docker README

---

osbenchmark/client.py
tests/client_test.py

Users have discovered that when invoked with `use_ssl:true` in the `client-options` parameter, OpenSearch-Benchmark runs into SSL issues for Python 3.10+. There's a misunderstanding in the code that `ssl.Purpose.CLIENT_AUTH` connects to client sockets when in reality it is `ssl.Purpose.SERVER_AUTH` that connects to client sockets (with or without certs).
As of Python 3.10, there are warnings and errors in place to prevent this from happening.  See #252 for information on what the issue looks like. 
This PR introduces a few small changes that prevents the SSL issue from coming up again in Python 3.10+. Added a few more unittests. 
#252 
- Manually tested across Python 3.10 and 3.11 and Python 3.8 and 3.9 for backwards compatibility 
- Added a couple …

Update client.py to handle SSL issue preventing connection to secure clusters (#252)

---

docker/Dockerfile
docker/README.md

This PR quickly updates the entrypoint in the Dockerfile by removing the `--help` flag to avoid conflicts. This is because when users append arguments -- such as `list workloads` -- to the sample command `docker run opensearchproject/opensearch-benchmark` found in the Docker README, it is the equivalent of running `opensearch-benchmark --help list workloads`. This is why it still presents the help screen instead of listing workloads.
```
docker run opensearchproject/opensearch-benchmark list workloads
usage: opensearch-benchmark [-h] [--version]
{execute_test,list,info,create-workload,generate,compare,download,install,start,stop}
...
/ __ \____  ___  ____ / ___/___  ____ …
```

Update entrypoint in Dockerfile

---

setup.py

Pypi still shows old maintainers. Just a quick PR to update this. 
#266 
N/A
---

Update Maintainers in Setup.py to match current Maintainers

---

osbenchmark/__init__.py
scripts/expand-data-corpus.py

This is a new capability intended to increase the size of the data corpora.  Currently, it is implemented only for the _http_logs_ workload.
https://github.com/opensearch-project/opensearch-benchmark/issues/254
- Tested script interactively in conjunction with independent changes to the _http_logs_ workload
- Ran the integ tests
---

Feature to increase the size of the data corpus for the http_logs workload

---

setup.py

Unblock Jenkins Workflow
```
[31mERROR   [0m HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
Invalid value for classifiers. Error: Classifier 'Topic :: System ::   
OpenSearch-Benchmark' is not a valid classifier.  
```
---

Update setup.py to update classifier

---

setup.py

Updating change to setup.py, that was dropped in change 00eaa79 (feature to increase the size of the data corpus for the http_logs)
https://github.com/opensearch-project/opensearch-benchmark/issues/254
---

Including setup.py change that was skipped in change 00eaa79.

---

CREATE_WORKLOAD_GUIDE.md
README.md
osbenchmark/benchmark.py
osbenchmark/resources/base-workload.json.j2
osbenchmark/resources/custom-query-workload.json.j2
osbenchmark/resources/default-query-workload.json.j2
osbenchmark/resources/workload.json.j2
osbenchmark/workload_generator/workload_generator.py

OSB's `create-workload` subcommand creates a custom workload based off of a specific index in a cluster. However, it only generates operations: 
- delete index
- create index
- cluster health check
- bulk ingestion into index
Users will benefit if the command is extended and allows users to provide queries to use. If no queries are specified, then the workload should come with a default query, such as `match_all` query, which is the simplest query that matches all documents in the index.
- For Jinja2 best practices, have renamed the current `workload.json.j2` to be `base-workload.json.j2`. This acts as a parent template that child templates -- `default-query-workloads.json.j2` and `custom-query-workloads.json.j2` -- inherit from. 
-if `create-workloads` subcommand invoked without …

Create workloads with default query or custom queries

---

osbenchmark/benchmark.py
osbenchmark/resources/custom-query-workload.json.j2
osbenchmark/resources/default-query-workload.json.j2
osbenchmark/utils/opts.py
osbenchmark/workload_generator/corpus.py
osbenchmark/workload_generator/workload_generator.py

`create-workload` currently fetches all documents from specified indices in `--indices`. Users should have the option to specify a subset of documents if they do not want to use all of the documents. In this PR, OSB now supports running `--total-docs` in conjunction with `--indices`. It takes in a comma-separated list of document counts that correspond to the respective index in the list of indices in `--indices`.
```
--indices=movies,actors --number-of-docs movies:1500 actors:1200
```
See #289 for more details.
#289 
Tested it with a few indices in private cluster. Tested the following cases:
- with single index and single doc count 
- with multiple indices and multiple doc counts
- with multiple indices and single doc count (should result in error as both doc counts need to be provided) …

Allow users to specify number of docs per index when creating workloads

---

PYTHON_SUPPORT_GUIDE.md
README.md
docs/api/execute-test.md
it/__init__.py
osbenchmark/benchmark.py
samples/ccr/start.sh
scripts/expand-data-corpus.py

As discussed in this issue #238, have opted to replace `execute_test` with `execute-test` to remain consistent. Ensured that methods in OSB called `execute_test()` remained unchanged.
#238 
Confirmed old invocation format does not work anymore
```
hoangia@3c22fbd0d988 opensearch-benchmark % opensearch-benchmark execute_test --workload=geonames --pipeline=benchmark-only --target-host="https://search-hoangia-aos-testing-2-xpwa7ykgv7bbc7qqfuuzt2no7i.us-east-1.es.amazonaws.com" --client-options="basic_auth_user:'hoangia',basic_auth_password:'Hoangia@123'" --test-mode
usage: opensearch-benchmark [-h] [--version] {execute-test,list,info,create-workload,generate,compare,download,install,start,stop} ...
opensearch-benchmark: error: argument subcommand: invalid choice: 'execute_test' (choose from …
```

Replace execute_test with execute-test

---

osbenchmark/utils/opts.py

Removing unnecessary `super().__init__()` in opts class.
N/A
Tested it again with create-workoads `--number-of-docs` feature and ran a test
---

Remove unnecessary super().__init__ in opts class

---

DEVELOPER_GUIDE.md
osbenchmark/workload/params.py
osbenchmark/workload/workload.py
tests/workload/params_test.py

Users are witnessing that OSB falls back silently to use LZ4 (default) index.codec when provided with an invalid index codec. OSB should check if the index.codec is valid and raise an error if it isn't. See #268 for more
#268 
- Added additional unittests
- Tested manually and got the outcome that was desired 
```
$ opensearch-benchmark execute-test \
--pipeline=benchmark-only \
--workload=geonames \
--target-host="<TARGET_ENDPOINT>" \
--client-options="basic_auth_user:'<USERNAME>',basic_auth_password:'<PASSWORD>'" \
--include-tasks=delete-index,create-index,index-append \
--workload-params='{"index_settings":{"index.codec": "this_should_be_invalid"}}' \
/ __ \____  ___  ____ / …
```

Validate index.codec when user provides as workload params

---

osbenchmark/metrics.py
tests/metrics_test.py

Users can now specify datastore password as environment variable instead of through plain text on config `benchmark.ini`
- Fixed unittests
- Tested it manually locally with no config and no env password, with config, and with env password only
---

Add support for providing datastore password via environment variable

---

.github/workflows/manual-integ.yml
DEVELOPER_GUIDE.md
Makefile
it/__init__.py
osbenchmark/resources/provision_configs/1.0/provision_config_instances/v1/vanilla/config.ini
osbenchmark/resources/provision_configs/main/provision_config_instances/v1/vanilla/config.ini
tox.ini

The integration tests are currently using obsolete versions of OpenSearch, 1.0.0 and 1.0.1.  This updates the versions to the newer ones in the v1 and v2 branches.  There is a separate batch of improvements to these tests, which will be checked in post the next OSB release.
Ran the integ tests on Ubuntu and Amazon Linux 2.  All passed.
On Mac, most of the tests passed, but there were occasional timeouts with one of the tests when runs were repeated.  This seemed to be the case even prior to these changes, so that will be made more robust separately.
--- …

Updating integ tests to use current versions of OpenSearch

---

.ci/build.sh
DEVELOPER_GUIDE.md
Makefile
it/__init__.py
osbenchmark/builder/builder.py
osbenchmark/resources/provision_configs/1.0/provision_config_instances/v1/vanilla/config.ini
osbenchmark/utils/console.py
osbenchmark/utils/process.py
tests/utils/console_test.py

Several fixes to the integration tests, which now also emit better error messages if and when the tests fail:
* Fixed `--kill-running-processes` which would kill the running process if the OSB repository is checked out as `opensearch-benchmark` instead of `OpenSearch-Benchmark`
* Capture stderr when integration tests are run, so error messages can be reported
* Disabled the `quiet` flag when the metrics store cluster is set up so errors are not lost
* Updated the console module to emit errors to stderr instead of stdout
* Updated the JDK version requirement for OpenSearch builds to version 17
* Updated the Makefile to check the JDK installation
* Updated the developer guide
#309 
Ran integ tests on RedHat, CentOS, Ubuntu, AL2 and MacOS.  There are two tests that fail on RedHat and CentOS …

More fixes for the integration tests

---

osbenchmark/resources/metrics-template.json

This change will increase the number of primary shards in the monthly index "benchmark-metrics-yyyy-mm" to accomodate more documents and avoid reaching the shard limit of 2B on the metrics data store.
We reached the max. number of 2 billion documents per shard in the monthly "benchmark-metrics-2023-05" index, a limit imposed by lucene, on our metrics data store which we use to rigorously benchmark domain(s). This doc limit was reached within first 3-4 days of the month. 
Considering this amount of data to be created consistently throughout the month , we made the decision to have 10 primary shards. We created a new index with 10 primary shards and re-indexed with new same-index index having 10 primary shards and 1 replica shard to make sure no data loss happens in case of node failures or …

Increase the shard and replica count for the benchmark-metrics-* indices in the data store

---

osbenchmark/workload/workload.py
tests/workload/params_test.py

This PR:
- Updates OSB to support ZSTD and ZSTDNODICT, two new codecs that are supported since OpenSearch 2.7.0+.
- Enhance error message to provide list of available codecs
```
"Please set the value properly for the create-index operation. Invalid index.codec value 'invalid_codec'. Choose from available codecs: ['default', 'best_compression', 'zstd', 'zstdnodict']"
```
#306 
Added new tests for ZSTD and ZSTDNODICT. Also added more description to show what available codecs there are for users. 
---
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRI …

Update Codec Enum to support ZSTD and ZSTDNODICT

---

DEVELOPER_GUIDE.md
README.md
it/resources/benchmark-in-memory-it.ini
it/resources/benchmark-os-it.ini
osbenchmark/benchmark.py
osbenchmark/config.py
osbenchmark/metrics.py
osbenchmark/publisher.py
osbenchmark/resources/benchmark.ini
osbenchmark/test_execution_orchestrator.py
osbenchmark/worker_coordinator/worker_coordinator.py
osbenchmark/workload/loader.py
osbenchmark/workload/workload.py
samples/ccr/start.sh
tests/config_test.py
tests/metrics_test.py
tests/publisher_test.py
tests/telemetry_test.py
tests/utils/console_test.py
tests/worker_coordinator/worker_coordinator_test.py

This PR addresses the following:
- Updates `results_publisher` to `publisher`
- Updates `publishing` to `reporting`
- Updates README to add documentation link and correct link to CREATE_WORKLOAD_GUIDE.md
- Updates DEVELOPER_GUIDE.md with important information how to get around conflict with unittests when `OSB_DATASTORE_PASSWORD` is set. 
#311 
#315 
- Ran `make test`
- Ran three benchmark tests -- one with in-memory data store, one with external OpenSearch cluster datastore with password in benchmark.ini, and one with external OpenSearch cluster datastore with password in environment variable. All three succeeded. Confirmed the external datastore tests had data properly ingested.
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

Update results_publisher to publisher

---

.github/ISSUE_TEMPLATE/proposal_template.md

This quick PR adds a new issue template to allow users to easily create RFCs and Proposals for OSB. This issue template provides a basic template of questions to address. 
N/A
N/A
---

Add Issue Template for RFCs and Proposals

---

osbenchmark/metrics.py
osbenchmark/resources/metrics-template.json
osbenchmark/resources/results-template.json
osbenchmark/resources/test-executions-template.json
tests/metrics_test.py

This PR allows users to set number_of_shards and number_of_replicas for `benchmark-*` indices. 
The changes introduced in PR #321 can potentially impact OSB users with varying datastore cluster configurations since it forces their datastore clusters to have `benchmark-metrics-*` indices of 10 primary shards and 2 replicas shards. 10 primary shards and 2 replica shards are not suitable for all kinds of OpenSearch clusters. A better solution is to offer flexibility and allow users to override the defaults imposed by OpenSearch (1 primary and 0 replicas according to the documentation). With this PR, users can now do this by setting their own primary and replica shards with the benchmark.ini config. See #330 for more information.
#330 #188 
See issue #330 for more testing.
---
By submitting …

Give users ability to set number_of_shards and number_of_replicas via datastore config

---

it/__init__.py
osbenchmark/utils/git.py
osbenchmark/utils/process.py
tests/utils/git_test.py

There were several errors with the `git` module.  The version check did not actually work.  Also, the error message generated when OSB atarted up if the git package was not installed, was not user-friendly:
```
ERROR] Cannot execute-test. Error in test execution orchestrator ([Errno 2] No such file or directory: 'git')
```
The git module tests were updated to incorporate the code changes.  There were some errors as well in the earlier tests, which resulted in some of then not actually working.
--- …

Fix issues with the git module

---

osbenchmark/workload/workload.py
tests/workload/params_test.py

This is to refactor the ```zstdnodict``` codec name to ```zstd_no_dict```
#335 
---

Refactoring zstdnodict to zstd_no_dict

---

jenkins/release.JenkinsFile

We recently upgraded the python version in the build repo. Due to this any code using build repo code fails if right python version is not used. Signing artifacts uses the build repo code hence updating the image to most recent one.
https://github.com/opensearch-project/opensearch-build/issues/3712
---

Update jenkins file to use updated docker image

---

osbenchmark/async_connection.py
osbenchmark/client.py
osbenchmark/metrics.py
setup.py
tests/client_test.py
tests/metrics_test.py

This PR adds support in OpenSearch benchmark to connect to OpenSearch clusters using SigV4 for running tests or reporting test results.
New configuration options added with this change:
1. New parameters supported with `--client-options` argument in `execute-test`:
- `amazon_aws_log_in`: Value can be one of `client-options` or `environment`
- if `amazon_aws_log_in` is  set as `client-options`, then the below configuration is mandatory in client-options:
- `aws_access_key_id`: The AWS access key ID to use
- `aws_secret_access_key`: The AWS secret key to use
- `service`: `es` for Amazon OpenSearch service
- `region`: The region in which the cluster is available, example: `us-east-1`
- if `amazon_aws_log_in` is  set as `environment`, then the below environment variables should be set:
- …

Adding SigV4 support to opensearch-benchmarks for connecting to test clusters and results publishing

---

osbenchmark/telemetry.py

OpenSearch Benchmark-1.0.0 cannot test ElasticSearch-7.10 and older versions due to change introduced in PR https://github.com/opensearch-project/opensearch-benchmark/pull/248. 
Upon hitting OpenSearch domain's endpoint, we get attribute "distribution" but this attribute is not defined for ElasticSeaech domains causing error in execute-test : 
`File "/home/ec2-user/.pyenv/versions/3.8.0/lib/python3.8/site-packages/osbenchmark/telemetry.py", line 629, in on_benchmark_start
distribution_name = default_client.info()["version"]["distribution"]
KeyError: 'distribution'`
This PR resolves adds a check to set variable **distribution_name** to empty string in case of ES domains and bypassing the error without impacting the existing functionality.
**execute-test** command now successfully …

Change to support benchmarking of ES-7.10 domains

---

osbenchmark/telemetry.py
osbenchmark/worker_coordinator/worker_coordinator.py
tests/telemetry_test.py

Add new telemetry device `Segment Replication Stats`.
It calls REST API `_cat/segment_replication` periodically to collect metrics such as replication lag.
The metrics output is all the fields in the response of the API https://opensearch.org/docs/2.8/api-reference/cat/cat-segment-replication/
As mentioned in issue https://github.com/opensearch-project/opensearch-benchmark/issues/339#issuecomment-1633207193, the existing code for "telemetry device" of "legacy" searchable snapshots stats and new ccr stats are taken as reference.
https://github.com/opensearch-project/opensearch-benchmark/blob/1.0.0/osbenchmark/telemetry.py#L969
https://github.com/opensearch-project/opensearch-benchmark/blob/1.0.0/osbenchmark/telemetry.py#L317 & commit …

Add a telemetry deivce - Segment Replication Stats

---

README.md
it/resources/benchmark-in-memory-it.ini
it/resources/benchmark-os-it.ini
osbenchmark/benchmark.py
osbenchmark/config.py
osbenchmark/metrics.py
osbenchmark/resources/benchmark.ini
osbenchmark/results_publisher.py
osbenchmark/test_execution_orchestrator.py
osbenchmark/worker_coordinator/worker_coordinator.py
osbenchmark/workload/loader.py
osbenchmark/workload/workload.py
samples/ccr/start.sh
tests/config_test.py
tests/metrics_test.py
tests/results_publisher_test.py
tests/telemetry_test.py
tests/utils/console_test.py
tests/worker_coordinator/worker_coordinator_test.py

In preparation for OSB 1.1.0 release, we need to remove any breaking changes that might have been introduced upstream. Found that this commit `40ed4613f3faa353a08b0418befcb1e907366041` adds a breaking change that should be introduced later for 2.0.0 release. 
Reverting checkbox in #351(https://github.com/opensearch-project/opensearch-benchmark/issues/351)
- Tested this on two workloads, percolator and geonames. Was able to get a report for both with 0% indexing errors. Also verified that the results_publishing config had no issues ingesting documents into external datastore.
---
For more information on following Developer Certificate of Origin and signing off your commits, …

Revert publisher back to results_publisher

---

osbenchmark/builder/builder.py
osbenchmark/client.py
tests/client_test.py

Serverless OpenSearch implementations don't support the full complement of OpenSearch APIs, since details of the internals such as node counts, allocation, shard locations, etc. are abstracted away.  For instance, the cluster-health API may not be available.  The changes here ensure that OSB will work for such systems.  There may be more changes required to ensure that flags like telemetry continue to function, but those issues will be handled in a subsequent change.
https://github.com/opensearch-project/opensearch-benchmark/issues/354
- Added a test to exercise the bypassing of the cluster health API call
- Ran unit and integ tests
---
For more information on following …

Changes for serverless implementations which may not support the full complement of OpenSearch APIs

---

osbenchmark/worker_coordinator/runner.py
osbenchmark/workload/workload.py
tests/worker_coordinator/runner_test.py

Add support for create search pipeline
Part of https://github.com/opensearch-project/OpenSearch/issues/7782
1. Unit test passed.
```
make test
================= 1185 passed, 5 skipped, 3 warnings in 20.11s =================
```
2. Added workloads and tested
```
{
"name": "create-http-log-baseline-search-pipeline",
"operation-type": "create-search-pipeline",
"id": "http-log-baseline-search-pipeline",
"body": {
"description": "Process search requests with a pipeline that does nothing. Baseline for overhead of pipeline."
}
}
|                                                 Min Throughput |          term |       45.65 |  ops/s |
|                                                Mean Throughput |          term |       45.65 |  ops/s |
| …
```

Add support for create search pipeline

---

DEVELOPER_GUIDE.md
README.md
osbenchmark/results_publisher.py

Shorten readme and improve developer guide
N/A
N/A
---

Update README and Developer Guide

---

setup.py

Bumping urllib3 to 2.3.2 and boto3 to 1.28.62 to satisfy it's dependencies. 
#378 
---

Bumping urllib3 and boto3

---

it/sources_test.py
osbenchmark/test_execution_orchestrator.py
tests/test_execution_orchestrator_test.py

If no pipeline is specified then by default 'benchmark-only' will be used
https://github.com/opensearch-project/opensearch-benchmark/issues/326
Tested against already running cluster without specifying pipeline. default 'benchmark-only' will be used
```
python3 benchmark.py execute-test --workload=http_logs --target-hosts=https://localhost:9200 --distribution-version=2.10.0 --client-options="basic_auth_user:'admin',basic_auth_password:'admin',verify_certs:false,use_ssl:false" --test-mode --kill-running-processes
Output logs
2023-10-10 03:17:48,323 -not-actor-/PID:52566 osbenchmark.test_execution_orchestrator INFO Test Execution id [452bd58d-31ee-4da5-86ed-b77339cfb411]
2023-10-10 03:17:48,324 -not-actor-/PID:52566 …
```

set default pipeline to benchmark-only

---

osbenchmark/client.py
osbenchmark/metrics.py
tests/client_test.py
tests/metrics_test.py

extend sigv4 support to role-based access
https://github.com/opensearch-project/opensearch-benchmark/issues/377
Added new UT
Updated existing UT
validated by running `make test`
validated by provisioning a managed cluster and verifying access with session-token
validated by running benchmark test using http_logs
**Note**
Scroll API request in OSB becnhmark test is failing and is currently being investigated
---

Extend Sigv4 to Role based Access

---

osbenchmark/utils/process.py
tests/utils/process_test.py

The -kill-running-processes flag does not work correctly on all platforms.  This change fixes the issue.
#404 
Ran unit and integ tests.  Updated one of the unit tests.
---

Fix the predicate used for the --kill-running-processes flag

---

osbenchmark/benchmark.py
osbenchmark/worker_coordinator/worker_coordinator.py
tests/worker_coordinator/worker_coordinator_test.py

The terminology used in Distributed Workload Generation is updated. 
Once all the hosts have had the daemon successfully start on them, we run the following command on the host we designated as --coordinator-ip.
opensearch-benchmark execute_test --pipeline=benchmark-only --workload=<workload> --load-worker-coordinator-hosts=<IP2,IP3> --target-hosts=<endpoint>
The parameter **"--load-worker-coordinator-hosts"** is renamed to **"worker-ips"** to be consistent with --node-ip and --coordinator-ip.
[258]
To use Distributed Workload Generation, users have to first start the opensearch-benchmark daemon on all hosts they plan to distribute load from. One of the hosts --referred to as the load coordinator host -- coordinates requests while the others -- referred to as worker-ips -- will drive the …

Rename parameters for Distributed Workload Generation - Issue 258 

---

DEVELOPER_GUIDE.md
osbenchmark/worker_coordinator/runner.py
osbenchmark/workload/workload.py
tests/worker_coordinator/runner_test.py

I have renamed the fields put-pipeline and all according names to create ingest pipeline.
Solves issue  #366 
No testing should be needed for renamed variables/classes.
Looked over by me and others to make sure 100% I got the name correct ( will be looked over again in PR )
---

renamed put pipeline to create ingest pipeline

---

osbenchmark/client.py
osbenchmark/utils/opts.py
setup.py

This PR implements the default Urllib3HttpConnection to replace RequestsHttpConnection to address the slower connection issue, as recommended by the opensearch-py guide for connection classes. Upon checking the code, I discovered this was the only place RequestsHttpConnection was used. Please do point out if I was wrong here.
#408 
---

Switching to the default connection class to address slower connection with RequestsHttpConnection

---

osbenchmark/worker_coordinator/runner.py
osbenchmark/workload/workload.py
tests/worker_coordinator/runner_test.py

For Vector search, we have to compare actual response's hits with expected neighbors to estimate recall for search. However, there is no provision to return recall similar to throughput. Hence, we will publish recall metrics like recall@k, recall@r as part of meta object. We also time those recall calculation and publish in ms to meta object.
Added tests to verify results are as expected.
Part of  https://github.com/opensearch-project/opensearch-benchmark/issues/103 
```
make test 
.venv/lib/python3.8/site-packages/pkg_resources/__init__.py:2868
.venv/lib/python3.8/site-packages/pkg_resources/__init__.py:2868
/Users/balasvij/PycharmProjects/knn/opensearch-benchmark/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py:2868: DeprecationWarning: …
```

Add vector search as new operation type to search

---

osbenchmark/exceptions.py
osbenchmark/utils/dataset.py
osbenchmark/utils/parse.py
setup.py
tests/utils/dataset_helper.py
tests/utils/dataset_test.py
tests/utils/parse_test.py

Vector Search Workloads usually uses dataset of type hdf5 and bigann. Hence, added support
to parse, partition those file formats. This will be later used by VectorSearch Param source in next pr.
part of #103 
```
make test
tests/utils/parse_test.py::ParseParamsFunctionalTests::test_parse_float_parameter_default PASSED [ 55%]
tests/utils/parse_test.py::ParseParamsFunctionalTests::test_parse_float_parameter_from_params PASSED [ 55%]
tests/utils/parse_test.py::ParseParamsFunctionalTests::test_parse_int_parameter_default PASSED [ 56%]
tests/utils/parse_test.py::ParseParamsFunctionalTests::test_parse_int_parameter_from_params PASSED [ 56%]
tests/utils/parse_test.py::ParseParamsFunctionalTests::test_parse_string_parameter_default PASSED [ 56%] …
```

Add dataset parser for vector search

---

osbenchmark/worker_coordinator/runner.py
osbenchmark/workload/params.py
tests/workload/params_test.py

Added new param source to partition vector dataset and
neighbors. This will be passed to runner to perform
search and compare response with neighbors for recall
calculation.
This param source extends Search ParamSource to inherit search's
other query parameters.
Vector Param Source will add additional paramter that are required
for vector serach operation type.
Part of #103 
```
make test
tests/workload/params_test.py::VectorSearchParamSourceTests::test_invalid_data_set_format PASSED [ 96%]
tests/workload/params_test.py::VectorSearchParamSourceTests::test_invalid_data_set_path PASSED [ 96%]
tests/workload/params_test.py::VectorSearchParamSourceTests::test_missing_params PASSED [ 96%]
tests/workload/params_test.py::VectorSearchParamSourceTests::test_par …
```

Add vector search param source

---

osbenchmark/worker_coordinator/runner.py
osbenchmark/workload/params.py
tests/worker_coordinator/runner_test.py
tests/workload/params_test.py

If custom field is used as unique field instead of _id, users can either enable _source to fetch those fields, or, use fields to include only return those fields with or without source. Hence, update parser to look for field name in fields first, and from _source at last.
Part of #103 
```
make test
tests/worker_coordinator/runner_test.py::QueryRunnerTests::test_query_vector_search_with_custom_id_field PASSED [ 64%]
tests/worker_coordinator/runner_test.py::QueryRunnerTests::test_query_vector_search_with_custom_id_field_inside_source PASSED [ 64%]
================= 1208 passed, 5 skipped, 3 warnings in 15.50s =================
```
---
For …

Add support to parse response if fields or _source are enabled

---

osbenchmark/utils/parse.py
osbenchmark/worker_coordinator/runner.py
osbenchmark/workload/params.py
osbenchmark/workload/workload.py
tests/workload/params_test.py

Added params and runner to support vector search
bulk operations. This custom bulk vector search
support partitioning files like bigann and hdf5
into multiple bulk request based on bulk size.
Part of #103 
```
make test
================= 1211 passed, 5 skipped, 3 warnings in 17.23s =================
```
---

Add vector search bulk param and runner

---

osbenchmark/benchmark.py
osbenchmark/worker_coordinator/runner.py
osbenchmark/worker_coordinator/worker_coordinator.py
osbenchmark/workload/workload.py
tests/worker_coordinator/runner_test.py
tests/worker_coordinator/worker_coordinator_test.py

OSCI program introduced some commits that rename components into main. However, these commits should be reverted to prevent breaking changes from entering OSB 1.2.0. These changes should only be included in the next major release, OSB 2.0.0. These changes are already cherry-picked into `renaming-components` branch.
- 3adacc0a9383cf7f81dbe0cba4c4f6c0b206cab2 Rename parameters for Distributed Workload Generation - Issue 258  (#407)
- e73664af95218a1ff1afb8fa05bc9d0c7766ec33 renamed put pipeline to create ingest pipeline (#399)
N/A
--- …

Revert renaming commits from main

---

osbenchmark/benchmark.py
osbenchmark/metrics.py
osbenchmark/results_publisher.py
tests/metrics_test.py

Adds a new optional argument, `--latency-percentiles`. The user specifies additional percentiles in a comma-separated list to be reported at the end of the workload, assuming the sample size is large enough for them to make sense. The existing percentiles (50, 90, 99, 99.9, 99.99, 100) are the default, but providing a value for `--latency-percentiles` overrides this.  
Example usage: 
`opensearch-benchmark execute-test --pipeline=benchmark-only --workload-path=/home/ec2-user/osb/opensearch-benchmark-workloads/modified_nyc_taxis --target-host=http://localhost:9200 --latency-percentiles=0,10,20,25,30,40,60,70,75,80,80.1,90.1,99.99`
Result: 
```| Min Throughput | cheap-dropoff | 85 | ops/s |
| Mean Throughput | cheap-dropoff | 85.01 | ops/s |
| Median Throughput | cheap-dropoff | 85.01 | …
```

Adds a command-line argument to specify more latency percentiles at the end of a workload. 

---

it/__init__.py
osbenchmark/utils/git.py
tests/utils/git_test.py

If git is not installed, the following error message is emitted, for instance, when a `list workloads` command is issued.  (A similar message appears for other commands like `execute-test` as well).
```
ERROR] Cannot list. [Errno 2] No such file or directory: 'git'.
```
This PR changes the message to:
```
[ERROR] Cannot list. Error invoking 'git', please install (or re-install).
```
The latter message had been added in change `0xd1eba717`, but was not active during the initial clone of the workloads repository.
Ran the unit tests and integ tests.  Had to update some of the existing tests, since the probe behavior is hardcoded.
---
For more information on following Developer …

Emit a more informative error message if git is not installed at startup

---

osbenchmark/workload/loader.py

Users have often made changes to OSB workloads and come across vague and unclear errors. Instead of showing them what the error is or providing them common issues and suggestions on how to fix them, the console wouuld show the following:
```
The complete workload has been written to '/var/folders/yh/89c2pcg10szgzwc6qj2h04gst115h_/T/tmptoxqvjsr.json' for diagnosis
```
These files are usually empty and not useful.
This PR adds better error handling when OSB attempts to render workload files and Jinja templates. Users do not have to dig into the OSB logs anymore for workload and jinja template errors or guess as to what went wrong. These changes now surface the error to the console and highlight common issues and solutions. 
#447 
Recreated common errors in `workload.json`, …

Surface Workload and Jinja Template Errors to Console and Provide Common Solutions

---

.github/CODEOWNERS
MAINTAINERS.md

Based on the [maintainer responsibilities for OpenSearch](https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#maintainer-responsibilities), we have decided to nominate the following individuals from the OSCI program to become maintainers of OSB:
- Mingyang Shi (@beaioun)
- Chinmay Gadgil (@cgchinmay)
N/A
N/A
---

Add maintainers after OSCI Autumn 2023

---

osbenchmark/utils/dataset.py
osbenchmark/workload/params.py
tests/workload/params_test.py

Param sources will be instatiated before corpora loading. Hence, set data set parameters to initial value during initialization and load data set during partition stage.
---

Move data set loading outside constructor

---

osbenchmark/workload/loader.py
osbenchmark/workload/workload.py

Previously we only support bulk as source format. We want to extend Documents to support more source formats.
However, not every format is similar. For Vector Search we want to use HDF5/BIG_ANN formats that don't support file offset table. Hence, add property to decide whether they support specific operation or not.
Part of #442 
---

Add new property to define operation

---

osbenchmark/benchmark.py
osbenchmark/workload/loader.py
osbenchmark/workload/params.py
tests/workload/loader_test.py
tests/workload/params_test.py

Allows the user to randomize the values in range queries in a controllable way. This allows reasonable tests of cache performance, where we can't use the same query repeatedly. 
To use this, in your workload's workload.py file, you must register a "standard value source" function in the register() function. This just means a function that takes no arguments and returns a dict of range values, with keys "gte", "lte", and optionally "format" (for dates). Usually you would want some randomness in this function, so that different values are produced every time you run it. During the workload, on each iteration, values from an output from this function get put into the range section of a query, and overwrite the default values. 
This registration is done on an operation and field level. For …

Adds controllable randomization to range queries in workloads

---

osbenchmark/workload/params.py
tests/workload/params_test.py

This commit allows vector search paramsource to accept corpus as dataset similar to bulk. 
Added tests to verify the corpus can be parsed and used as dataset path/neighbor's dataset path/query's dataset path.
Part of #442 
```
tests/workload/params_test.py::VectorSearchParamSourceTests::test_corpus_contains_more_than_one_files PASSED [ 95%]
tests/workload/params_test.py::VectorSearchParamSourceTests::test_corpus_not_found_in_workload PASSED [ 95%]
tests/workload/params_test.py::VectorSearchParamSourceTests::test_invalid_data_set_format PASSED [ 95%]
tests/workload/params_test.py::VectorSearchParamSourceTests::test_invalid_data_set_path PASSED [ 95%]
tests/workload/params_test.py::VectorSearchParamSourceTests::test_missing_corpus PASSED [ 95%] …
```

Add support to use corpus for vector search params

---

osbenchmark/workload/params.py
tests/workload/params_test.py

if filter is passed as params, copy filter value as efficient
filter to vector search query body.
```
updated existing test to check filter
================= 1221 passed, 5 skipped, 4 warnings in 16.58s =================
```
---

Add support to pass efficient filter body to vector search params

---

osbenchmark/worker_coordinator/worker_coordinator.py
tests/worker_coordinator/worker_coordinator_test.py

Fixed client processing time
Fixed an issue raised with client processing time addition. 
https://github.com/opensearch-project/opensearch-benchmark/pull/450#issuecomment-1936836969
I tested it in most of the cases where OpenSearch call fails.  
---

Fixed client processing time

---

osbenchmark/workload/params.py
tests/utils/dataset_helper.py
tests/workload/params_test.py

If neighbor's dataset path or corpus is not set,
use dataset path as neighbor's dataset path. This will avoid
users to set neighbors dataset path if same h5 file with
different dataset is used.
---

Make neighbor's dataset path as optional

---

osbenchmark/worker_coordinator/runner.py

Enhance client processing time calculation in the ForceMerge Runner to address a critical issue. This improvement rectifies an error encountered when utilizing polling, where the force merge times out during the initial call **without raising an exception**, and subsequently completes successfully. Previously, the request_context_holder.on_client_request_end() wasn't appropriately calculated in such scenarios. For further context, please refer to the discussion [here](https://github.com/opensearch-project/opensearch-benchmark/pull/450#issuecomment-1962750962).
https://github.com/opensearch-project/opensearch-benchmark/pull/450#issuecomment-1962750962
- Tested by @VijayanB [here]( https://github.com/opensearch-project/opensearch-benchmark/pull/450#issue …

Fix client processing time calculation in ForceMerge Runner

---

.github/CODEOWNERS
MAINTAINERS.md

Elected to add Rishabh as a maintainer after reviewing his work for OpenSearch project and OSB. 
---

Add Rishabh as maintainer after vote

---

setup.py

This change updates the setup file for Jinja2 from version 2.11.3 to 3.1.3 to resolve the CVE in the older version.
#481 
Test locally and through Github Actions
The Jinja2 3.1.3 was tested to be compatible with OSB
---

Bumping Jinja2 to version 3.1.1 for CVE

---

setup.py

This contains fix to accept wait_for_completion parameter for index force merge api.
---

Update opensearch-py to 2.5.0

---

osbenchmark/benchmark.py

display test execution id before running test for start and execution-test commands. These are the only 2 subcommands which use this argument.
#471 
Ran without custom test execution id
```
python3 osbenchmark/benchmark.py execute-test --pipeline=benchmark-only --workload=percolator --target-host=https://localhost:9200/ --client-options=basic_auth_user:admin,basic_auth_password:admin,verify_certs:false --test-mode                                     
[INFO] [Test Execution ID]: a7b0f002-573c-41c6-a2fb-8df7d9ad0ff6
[INFO] You did not provide an explicit timeout in the client options. Assuming default of 10 seconds.
[INFO] Executing test with workload [percolator], …
```

Always print test_execution_id

---

osbenchmark/worker_coordinator/runner.py

Adding "request-params" support for bulk operation.
- https://github.com/opensearch-project/opensearch-benchmark/issues/500
---

Support request-params for bulk operation

---

osbenchmark/benchmark.py
osbenchmark/results_publisher.py

Currently, users running with `compare` subcommand are only seeing P100 latency and service time in the results. This PR adds to previous changes made by Peter Alfonsi and allows users to specify which percentiles they want displayed. If no percentiles are passed through, the default percentiles in the GlobalStatsCalculator is used, similar to how it is used in `--latency-percentiles` and `--throughput-percentiles` params in `execute-test` subcommand.
#503 
When enough data is present, it will show all percentiles specified. 
```
hoangia@3c22fbd0d988 opensearch-benchmark % opensearch-benchmark compare --baseline ffe95f09-e5f0-4acf-965c-ab7c88cff083 --contender ffe95f09-e5f0-4acf-965c-ab7c88cff083
____                  _____                      __       ____                  __ …
```

Allow users to specify percentiles for compare subcommand (#503)

---

osbenchmark/worker_coordinator/runner.py
tests/worker_coordinator/runner_test.py

Worker coordinator expects every runner to have request start and request end key.
Added client request start and client request end before and after sleep.
#485 
---

Add request start and end parameter to sleep runner

---

osbenchmark/resources/metrics-template.json

With the addition of segment replication related fields in the `node-stats` telemetry the total number of fields in the `benchmark-metrics-*` indices exceed the default limit of 1000. This results in `Limit of total fields [1000] in index [benchmark-metrics-04-2024] has been exceeded` errors in datastore cluster. 
This PR increases the default limit to 2000. 
---

Increase 'mapping.total_fields.limit' to '2000'

---

osbenchmark/worker_coordinator/runner.py
osbenchmark/workload/workload.py

Added runners DeletePipeline, DeleteMlModel, RegisterMlModel and DeployMlModel. So that we can run the new workload semantic_search, that does indexing and search with vector embedding.
https://github.com/opensearch-project/opensearch-benchmark-workloads/issues/198
Tested by executing the neural_search workload
---

Added runners to register and deploy ml-model

---

osbenchmark/worker_coordinator/runner.py
tests/worker_coordinator/runner_test.py

Change force merge polling logic to use wait_for_completion
to false, to make it async and use task's get api to check
whether task is completed or not to exit from force merge.
Here, request end time is calcuated only after task is completed.
This request end time will not be 100% accurate, since, we use polling to check
whether task status is completed or not.
---

Update force merge polling

---

RELEASE_GUIDE.md
docker/Dockerfile
osbenchmark/benchmark.py

Prevents bottleneck at build release. Also, added misc. doc updates.
---

Update h5py in dockerfile

---

osbenchmark/utils/dataset.py
tests/utils/dataset_helper.py
tests/utils/dataset_test.py

Bigann stores ground truth in different format than vector dataset. In this commit, added new dataset that is used by big-ann for ground truth.
#530 
- make test
- Locally tested with bigann neighbor dataset as input and verified that recall is 0.998
---

Add support to big-ann ground truth file format

---

.github/CODEOWNERS
MAINTAINERS.md
setup.py

Adding @VijayanB as a maintainer as voted upon by the existing maintainers of OpenSearch Benchmark project per the [maintainer guidelines](https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#becoming-a-maintainer).
Vijayan has made numerous contributions to OSB code that supports running benchmarks on vector workloads.
Please find all his contributions below:
- [OpenSearch Benchmark Repository Contributions](https://github.com/opensearch-project/opensearch-benchmark/pulls?q=is%3Apr+author%3AVijayanB)
- [OpenSearch Benchmark Workloads Repository Contributions](https://github.com/opensearch-project/opensearch-benchmark-workloads/pulls?q=is%3Apr+is%3Aclosed+author%3AVijayanB)
By submitting this pull request, I confirm that my contribution is made under the terms of …

Adding Vijayan as OpenSearch Benchmark Maintainer

---

osbenchmark/workload/loader.py
tests/workload/loader_test.py

Generation of the offset table that maps line numbers to file offsets for large data corpora can take a considerable amount of time.  Downloading pre-generated offset files is much faster.  This change implements this capability and downloads associated offset files when available.
#519 
- Ran unit and integration tests.
---

Download pre-generated offset file from data corpus repository, if present

---

osbenchmark/utils/process.py

On Linux, /proc/PID/status truncates the command name to 15 characters which matches both opensearch-benchmark and opensearch-benchmarkd. Adding an additional check to exclude opensearch-benchmarkd process.
Validated by running benchmark daemon on three nodes and then by running execute test with ```--load-worker-coordinator-hosts``` option. The test ran fine on the worker nodes.
---

Excluding opensearch-benchmarkd process while finding benchmark process

---

osbenchmark/utils/process.py
tests/utils/process_test.py

On linux, the process name is truncated to 15 characters and hence it matches both opensearch-benchmark and opensearch-benchmarkd. This results in killing the daemon process and breaks the distributed run setup. Removing the name based check on the truncated name and relying on command line which provides the full command.
Keeping the name based check on full name as is.
Tested in Linux system and verified daemon process is excluded in duplicate process check.
---
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of- …

Removing the duplicate process check based on truncated name and relying on cmdline check

---

MAINTAINERS.md

Adding maintainer email addresses to MAINTAINERS.md
---

Add email addresses for Maintainers on MAINTAINERS.md

---

docker/Dockerfile
setup.py

Version 1.7.0 encountered a bug when we use h5py 3.10.0 and numpy 2.0.0 (which was recently released). Currently, Dockerfile contains a line that forces h5py 3.10.0, which was used to unblock an issue in Jenkins a few months ago. For more, details, see this [issue](https://github.com/opensearch-project/opensearch-benchmark/issues/545).
```
benchmark@b7e33afd6ad6:~$ pip3 list
Package                   Version
------------------------- -----------
...
h5py                      3.10.0
numpy                     2.0.0
...
benchmark@b7e33afd6ad6:~$ opensearch-benchmark --version
Traceback (most recent call last):
File "/usr/local/bin/opensearch-benchmark", line 5, in <module>
from osbenchmark.benchmark import main
File "/usr/local/lib/python3.11/site-packages/osbenchmark/benchmark.py", line 37, …
```

Fix Numpy & h5py bug in 1.7.0

---

docker/Dockerfile

Dockerbuild job in Jenkins is currently blocked when building images for ARM. Add back h5py restriction in Dockerfile to unblock Docker Build for ARM images.
Tested this in a c6g.large EC2 instance and reproduced it. Confirmed build and image works after we added this line back in.
---

Add back h5py restriction in Dockerfile to unblock Docker Build for ARM images

---

docker/Dockerfile

Backport from #568 merged in mainline
---

Add back h5py restriction in Dockerfile to unblock Docker Build for ARM images (#568)

---

triage.md

This PR is to start gathering feedback and update triage.md
NA
rendered the markdown in local setup
---

added Triage document for weekly triages

---

Makefile
docker/Dockerfile

`h5py` wheels are supplied for different versions on Intel and ARM architectures, and the build from source of this package is not straightforward, leading to issues during the OSB release.  This change ensures that a source build is not attempted.
#570 
Built OSB manually on both `x86` and `aarch64`.
---

Fix h5py build issues encountered during the release process

---

.github/workflows/backport.yml

Bringing over the backporting Github Actions from workloads repository to this one. This will help backporting changes from main to other branches like 1.7. 
#565 
---

Backport feature for easier backport when patching

---

osbenchmark/benchmark.py
osbenchmark/workload/loader.py

https://github.com/opensearch-project/opensearch-benchmark/pull/455 introduced a way to controllably randomize range queries in workloads, which is useful in testing caching behavior. One relevant parameter is Zipf alpha, which changes the shape of the Zipf distribution used for repeated queries. If alpha is small, queries will be more evenly distributed, while if it's large the few most common queries will be preferred more. 
I intended to include this as a flag in my original PR but I apparently forgot to do this, and currently alpha is hardcoded to 1. This PR exposes `--randomization-alpha` so the user can set this value explicitly. 
N/A
Manually tested in a debug version of this branch, by checking the value of the flag made it to QueryRandomizerWorkloadProcessor.zipf_alpha, and …

Adds --randomization-alpha flag controlling distribution of repeated queries

---

osbenchmark/metrics.py
osbenchmark/results_publisher.py
osbenchmark/worker_coordinator/worker_coordinator.py
tests/metrics_test.py

Displays recall as part of the final benchmarking stats.
i.e.: 
```
------------------------------------------------------
_______             __   _____
/ ____(_)___  ____ _/ /  / ___/_________  ________
/ /_  / / __ \/ __ `/ /   \__ \/ ___/ __ \/ ___/ _ \
/ __/ / / / / / /_/ / /   ___/ / /__/ /_/ / /  /  __/
/_/   /_/_/ /_/\__,_/_/   /____/\___/\____/_/   \___/
------------------------------------------------------
|                                                         Metric |                     Task |       Value |   Unit |
|---------------------------------------------------------------:|-------------------------:|------------:|-------:|
|                     Cumulative indexing time of primary shards |                          |     16.1933 |    min | …
```

Publish recall as a kpi metric

---

docker/Dockerfile

When building Docker image for ARM64, we're still hitting the same error we encountered before. To unblock build error in Jenkins, we need to add this [change](https://github.com/opensearch-project/opensearch-benchmark/pull/574) (that was originally added to the Makefile in this PR) to the Dockerfile.
1. Built Dockerfile with this change
2. Imported h5py and verified binaries were used. As seen below, methods and properties are viewable, implying that binaries (precompiled) was selected over tar.gz
```
benchmark@d1b42b9974e2:~$ python3
Python 3.11.2 (main, Mar 23 2023, 03:00:37) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>> dir
KeyboardInterrupt
>>> dir(h5py)
['AttributeManager', 'Dataset', 'Datatype', 'Empty', …
```

Add PIP_ONLY_BINARY to Dockerfile

---

osbenchmark/worker_coordinator/runner.py
osbenchmark/workload/workload.py
tests/worker_coordinator/runner_test.py

Added EnableConcurrentSegmentSearch runner, this will be used in semantic search workloads like https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/noaa_semantic_search or one that is in PR https://github.com/opensearch-project/opensearch-benchmark-workloads/pull/342 
building block for https://github.com/opensearch-project/opensearch-benchmark-workloads/issues/341
---

Added runners for enabling concurrent segment search via settings

---

osbenchmark/builder/utils/template_renderer.py
osbenchmark/workload/loader.py
tests/builder/utils/template_renderer_test.py

Customizing workloads to operate differently on different versions of OpenSearch is convoluted.  This change adds a Jinja filter `version_between` that can be used to test if an OpenSearch version falls within a specified range of versions.  For instance, a workload can be customized to operate in a backward-compatible way on OpenSearch 1.X and use updated capabilities on OpenSearch 2.X.
#548 
Added a test, ran unit and integ tests.
---

Add a Jinja filter to aid with version checking

---

jenkins/release.JenkinsFile

Preset opensearch-benchmark-git dir to support dockerfile change in #601
https://github.com/opensearch-project/opensearch-build/issues/4723
---

Preset opensearch-benchmark-git dir to support dockerfile change in #601

---

osbenchmark/worker_coordinator/runner.py
tests/worker_coordinator/runner_test.py

Need to correct setting name for recently added runner EnableConcurrentSegmentSearch. As per [documentation](https://opensearch.org/docs/latest/search-plugins/concurrent-segment-search/) correct setting name is `search.concurrent.max_slice_count`. With current setting name the runner and calling operation will fail.
Original PR https://github.com/opensearch-project/opensearch-benchmark/pull/591
---

Corrected setting name for max_slice_count

---

it/resources/benchmark-os-it.ini
osbenchmark/utils/dataset.py
osbenchmark/worker_coordinator/runner.py
osbenchmark/workload/params.py
tests/worker_coordinator/runner_test.py
tests/workload/params_test.py

Since OpenSearch version 2.14, we've introduced vector [radial search](https://opensearch.org/docs/latest/search-plugins/knn/radial-search-knn/) in k-NN plugin, this PR will support run benchmark with radial search api.
Raised another PR https://github.com/opensearch-project/opensearch-benchmark-workloads/pull/309 in opensearch-benchmark-workloads to have the change accordinately.
Example local run workloads and results:
```
{
"target_index_name": "target_index",
"target_field_name": "target_field",
"target_index_body": "indices/faiss-index.json",
"target_index_primary_shards": 3,
"target_index_dimension": 768,
"target_index_space_type": "innerproduct",
"target_index_bulk_size": 100,
"target_index_bulk_index_data_set_format": "hdf5",
"target_index_bulk_index_data_set_path": …
```

Add benchmark support for vector radial search

---

docker/Dockerfile-development
docker/docker-compose-tests.yml

Integration tests are currently searching for `docker-compose-tests.yml` which was removed yesterday. Adding it back in.
Example
```
ERROR it/sources_test.py::test_sources[in-memory-it] - FileNotFoundError: [Errno 2] No such file or directory: 'docker-compose'
```
---

Add docker-compose-tests.yml back in to fix integ tests

---

scripts/expand-data-corpus.py
tests/scripts_test.py

Better warning messages and some minor fixes.
#600
Ran the script in several scenarios including within Docker.

Updates to the expand-data-corpus script

---

osbenchmark/builder/builder.py

As mentioned by @gkamat, when provisioning a cluster in OSB, the master node specification should match the node name. This change ensures that these two values always match, by performing a check before building the cluster and ensuring the two values match before moving on.
[#380](https://github.com/opensearch-project/opensearch-benchmark/issues/380)
- [✔️] New functionality includes testing
tested with `make test` + `make it` and by provisioning clusters with mismatched values, as well as missing values for either node-name or master-node value.
--- …

add default value for master-node when provisioning cluster using OSB

---

osbenchmark/utils/dataset.py
osbenchmark/utils/parse.py
osbenchmark/worker_coordinator/runner.py
osbenchmark/workload/params.py
tests/utils/dataset_helper.py
tests/worker_coordinator/runner_test.py
tests/workload/params_test.py

This change adds support for ingesting non-vector fields from an HDF5 dataset into OpenSearch k-NN. It also adds support for writing post-filtering queries. These changes aid the transition from k-NN's perf tool to using OSB for release benchmarking. 
Please see [OSB Workloads PR 364](https://github.com/opensearch-project/opensearch-benchmark-workloads/pull/364) for usage examples. 
Unit tests were added that cover the new param and runner methods. Additionally all of the functionality has been tested via the parameter files in [OSB Workloads PR 364](https://github.com/opensearch-project/opensearch-benchmark-workloads/pull/364).
---
For more information on following Developer …

Add approximate filters

---

.ci/build.sh
.github/workflows/docker-build.yml
.github/workflows/integ-test.yml
.github/workflows/unit-test.yml
DEVELOPER_GUIDE.md
Makefile
docker/Dockerfile
setup.py

Restructured the entire OSB build system, including standalone, Docker and via GitHub actions.
Tested out most combinations of the workflows above.
---

Refactored the OSB build system

---

osbenchmark/results_publisher.py
osbenchmark/workload/loader.py
tests/workload/loader_test.py

Finding the maximum search throughput for an OpenSearch cluster is an important benchmarking scenario in vector search. Currently the only way to figure out the maximum search throughput is to perform multiple benchmark runs with different search client settings (e.g. search_clients = 3, search_clients = 5, ...). Waiting for a run to conclude, changing the config, and rerunning OSB with the associated startup time is tedious. Ideally the maximum throughput could be found automatically.
This PR allows users to provide a `clients_list` in a operation which runs the operation with each client setting. 
For instance, a user might specify `"clients_list": [1, 5]` in their parameters.
Then OSB will schedule search tasks with 1, 5, 10, and 12 clients. The final benchmark results will look …

Specify multiple search clients for easier benchmarking

---

jenkins/release.JenkinsFile

Add tag as the release branch in jenkinsfile release
Closes https://github.com/opensearch-project/opensearch-benchmark/issues/641
---

Add tag as the release branch in jenkinsfile release

---

.ci/build.sh
.github/workflows/docker-build.yml
.github/workflows/integ-test.yml
.github/workflows/publish-release.yml
.github/workflows/unit-test.yml
DEVELOPER_GUIDE.md
Makefile
docker/Dockerfile
setup.py

Cherry pick of build changes in main, includes fix for #636.
---

Build updates and fix for docker mount issue in v1.9

---

jenkins/release.JenkinsFile

This error was encountered in Jenkins:
```
WorkflowScript: 19: illegal string body character after dollar sign;
solution: either escape a literal dollar sign "\$5" or bracket the value expression "${5}" @ line 19, column 70.
SCRIPT_WITH_COMMANDS', value: [
^
1 error
```
Adding a quick fix. 
---

Address string issue in Groovy

---

RELEASE_GUIDE.md

After encountering a few issues in the release process, we updated the release guide.
---

Update release guide with more details

---

osbenchmark/aggregator.py
osbenchmark/benchmark.py
osbenchmark/metrics.py
tests/aggregator_test.py

Adds the aggregate feature, allowing users to aggregate multiple test executions into one aggregated test result. Also compatible with other features such as `compare`
To aggregate multiple test executions, you can use the aggregate command like so:
`opensearch-benchmark aggregate --test-executions=<test_execution_id1>,<test_execution_id2>,...`
Sample output:
```
/ /_/ / /_/ /  __/ / / /__/ /  __/ /_/ / /  / /__/ / / /  / /_/ /  __/ / / / /__/ / / / / / / / …
```

Add aggregate command

---

osbenchmark/aggregator.py

Aggregated test results were not working properly when being used with OSB's `compare` command. This is because `op_metrics` was being spelled as `op-metrics` (using a dash instead of an underscore).
#656 
---

change op-metrics to op_metrics in aggregator file

---

osbenchmark/utils/opts.py
osbenchmark/workload_generator/extractors.py
osbenchmark/workload_generator/helpers.py
osbenchmark/workload_generator/workload_generator.py

Currently, there's a bug in create-workload when users specify the number of docs to extract from an index. Addressing the fix in this PR. This PR also adds more error handling  and warnings to streamline user experience.
#658 
Tested with these scenarios:
- Running create-workload with 2+ number of docs entries
- Testing number of docs entry with 0 or less docs
- Testing number of docs entry with less than 1K docs
- Testing number of docs entry that does not exist in the cluster
```
(.venv) hoangia@80a9971b1103 opensearch-benchmark % opensearch-benchmark create-workload --target-hosts=XXXXXX --client-options=basic_auth_user:'XXXXXX',basic_auth_password:'XXXXXX' --indices=movies-1000,movies-2000,nyc_taxis  --output-path=~/Desktop/ --workload=test-workload …
```

Fix --number-of-docs bug in create-workload

---

osbenchmark/aggregator.py
osbenchmark/benchmark.py

This change allows users to run benchmark tests with any configuration they choose, for `x` number of iterations, then generate an aggregated results at the end, all in one command!
Here's an example command:
`opensearch-benchmark auto-aggregate --test-iterations=2 --workload=geonames --target-hosts=127.0.0.1:9200`
The auto-aggregate argument parser inherits from the test-execution argument parser, so you can use any arguments/flags that you would use on a regular test execution:
`opensearch-benchmark auto-aggregate --test-iterations=2 --workload=geonames --target-hosts=127.0.0.1:9200 --test-mode --kill-running-processes`
And these will be applied to each test execution.
#631 
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

add automatic testing and aggregation to OSB

---

osbenchmark/resources/workload-schema.json
osbenchmark/workload/loader.py
osbenchmark/workload/workload.py
tests/workload/loader_test.py

Permits data corpus files to be downloaded in parts.  This is not intended for performance, but rather, to work around the restriction on file size that services like CloudFront might have.
#543 
Lint, unit and integ tests.  Added a unit test to exercise the feature.
---

Add support for multi-part data corpora downloads

---

osbenchmark/benchmark.py

Adds short-hand alternatives for commonly used command line options in OSB.
Now, rather than running:
`opensearch-benchmark execute-test --workload=geonames --target-hosts=127.0.0.1:9200 --test-mode --kill-running-processes`
one can instead run:
`opensearch-benchmark execute-test -w=geonames -th=127.0.0.1:9200 --test-mode -krp`
#639 
Tested by using shorthand alternatives for the commands changed.
---

Add shorthand alternatives for command line options in OSB

---

.github/ISSUE_TEMPLATE/documentation_template.yml

Now that we have [this board ](https://github.com/orgs/opensearch-project/projects/228/views/1)for documentation, we should create an issue template to easily create issues for documentation.
---

Add new issue template

---

osbenchmark/aggregator.py

Adds relative standard deviation to aggregated test result metrics. Users can now see the spread of their OSB test results. (RSD is currently only calculated for the mean)
Example:
```
{
"task": "wait-until-merges-finish",
"operation": "wait-until-merges-finish",
"throughput": {
"min": 74.41136845553248,
"mean": 74.41136845553248,
"median": 74.41136845553248,
"max": 74.41136845553248,
"unit": "ops/s",
"mean_rsd": 5.7260883182218825
},
"latency": {
"100_0": 12.996128527447581,
"mean": 12.996128527447581,
"unit": "ms",
"mean_rsd": 5.875897232448762
},
"service_time": {
"100_0": 12.996128527447581,
"mean": 12.996128527447581,
"unit": "ms",
"mean_rsd": 5.875897232448762
},
"client_processing_time": {
"100_0": 0.6900834268890321,
"mean": 0.6900834268890321,
"unit": "ms",
"mean_rsd": …
```

add relative standard deviation to aggregated test execution metrics

---

.github/CODEOWNERS
MAINTAINERS.md

@OVI3D0 has contributed numerous changes to the OpenSearch Benchmark ecosystem. Some notable contributions he's made include implementing of the aggregation feature that debuted in OSB 1.10.0, enabling OSB to run multiple test iterations, and simplifying the user experience in OSB workloads.
To see more on his contributions, see the following links:
**OpenSearch Benchmark Repo:**
PRs: https://github.com/opensearch-project/opensearch-benchmark/pulls?q=is%3Apr+author%3AOVI3D0
Issues: https://github.com/opensearch-project/opensearch-benchmark/issues/created_by/OVI3D0
**OpenSearch Benchmark Workloads Repo:** 
PRs: https://github.com/opensearch-project/opensearch-benchmark-workloads/pulls?q=is%3Apr+author%3AOVI3D0
Issues: https://github.com/opensearch-project/opensearch-benchmark-workloads/issu …

Add new maintainer Michael Oviedo

---

osbenchmark/workload/params.py

Remove unnecessary logging
---

Remove unnecessary logging

---

osbenchmark/aggregator.py
osbenchmark/results_publisher.py
tests/aggregator_test.py
tests/results_publisher_test.py

This change updates min/max values in aggregated test results, to reflect the overall min/max values across all test executions, rather than just the average of each. The names of these values have also been prefixed with `overall_` in order to reflect these changes. Changes were also made to the `ComparisonResultsPublisher` class, so these values can still be read if used in a `compare` command. Tests were also updated to reflect the recent changes to the aggregator class, and also to test the `ComparisonResultsPublisher` class.
#684 
`make test`
--- …

Change min/max to overall_min/overall_max + update comparison results publisher

---

osbenchmark/utils/opts.py
osbenchmark/workload/loader.py
tests/utils/opts_test.py

When the argument passed to the `workload-params` option includes a key-value pair, where the value is a JSON file, there parser may treat the entire option string incorrectly as a filename. 
#502 
Unit and integ tests.  Added unit tests.
---

Fix workload parameter processing when a key is mapped to a JSON file

---

osbenchmark/worker_coordinator/runner.py
osbenchmark/worker_coordinator/worker_coordinator.py
osbenchmark/workload/params.py
tests/worker_coordinator/runner_test.py
tests/workload/params_test.py

When the number of search clients is greater than the number of cpu cores [recall drops unexpectedly](https://github.com/opensearch-project/opensearch-benchmark-workloads/issues/347). @VijayanB is investigating the cause, but this PR throws a warning if num_clients > the cpu cores available and skips calculating the recall. It also adds a parameter `calculate-recall` to specify whether or not to calculate recall (either `calculate-recall: true` or `calculate-recall: false`).
Unit tests.
Also tested on mac with 12 cores. Skips recall calculation if num_clients > 12, calculates recall otherwise. `calculate-recall` parameter works as expected. Will add unit tests in a second PR by EOD.
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

Add calculate-recall parameter to vector search and skip calculating recall if number clients > cpu cores

---

osbenchmark/aggregator.py
tests/aggregator_test.py

Recently, OSB workloads were updated to include parameters for users to input custom iteration values in their test executions. This change gives the new aggregate command the ability to read these values and take them into account when calculating the average values for test executions.
Previously, iterations for each task were stored as a sum of iterations across all test execution. With this change, the iterations for each task are stored separately, so a test with x times the iterations of another will also hold that much more weight in the average calculation.
Also updates the unit tests to reflect the new changes.
#670 
`make test`
---
For more information on following …

Add support for custom iteration values

---

.github/workflows/integ-test.yml
.github/workflows/unit-test.yml

Seems there was a missing dependency causing integ tests + unit tests for ubuntu to fail. This change adds a step to update + install libbz2-dev which should resolve this issue.
Running github actions with new yaml files
---

update integ-test + unit-test yaml files

---

osbenchmark/worker_coordinator/runner.py

Some of the URL paths in change `794e11ed6` were missing a slash character.
#718 
Ran the workload described in the issue.
---

Fix URLs for ml-model runners

---

osbenchmark/workload/loader.py
osbenchmark/workload/params.py
tests/workload/loader_test.py
tests/workload/params_test.py

Controllable query randomization was added in https://github.com/opensearch-project/opensearch-benchmark/pull/455, and was limited to randomizing `range` queries with fields `gte`/`gt`, `lte`/`lt`, and optionally `format`. This is limiting since we might need to randomize other queries for some use cases, like benchmarking the query cache. 
This PR lets the user register different query names and parameter names to be randomized for each operation. This is done by adding `registry.register_query_randomization_info(...)` in workload.py. See an [example](https://github.com/peteralfonsi/opensearch-benchmark-workloads/blob/geopoint-nyc-taxis/nyc_taxis/workload.py#L86). 
In this example we have the operation: 
```
{
"name": "bbox", 
"operation-type": "search", 
"index": "nyc_taxis",
"body": { …
```

Make query randomization more flexible

---

it/__init__.py
osbenchmark/paths.py
osbenchmark/utils/io.py

Updates OSB's config directory to ~/.osb instead of ~/.benchmark. Also adds a symlink if the old path exists but the new one does not. 'benchmark' is an overloaded term, while using ~/.osb reduces ambiguity and is more consistent with the project's name.
#728 
`make test` + `make it`
---

Change OSB Config directory from `~/.benchmark` to `~/.osb`

---

.ci/build.sh
.github/workflows/integ-test.yml

Integration tests were failing due to recent changes in OpenSearch that require Java 21 for gradle builds:
```
* What went wrong:
A problem occurred evaluating project ':buildSrc'.
> At least Java 21 is required to build opensearch gradle tools
```
([reference to the failing tests](https://github.com/opensearch-project/opensearch-benchmark/actions/runs/12936541840/job/36084369757?pr=720#step:9:410)). 
[Reference to the OpenSearch PR that updates the JDK version](https://github.com/opensearch-project/OpenSearch/commit/7c46f8f14e1beefdd24eb2fe61792c6737fe9023#diff-bc7a42af0a917334e95bb43c1ac3408e14a03a45ef844e044089d4dc233d5b74R77-R78).  
To fix this, I added a JDK 21 installation to the integ tests for the gradle builds. However, a JDK version between 11 and 17 is still needed for the …

update to JDK 21 for integ tests

---

osbenchmark/worker_coordinator/worker_coordinator.py

Adds more detailed error messaging to the console if a request fails or if a workload is improperly configured. 
Example:
```
[ERROR] Cannot execute-test. Benchmark operation failed:
Worker ID: 0
Task: index-statrs
Workload: geonames
Test Procedure: append-no-conflicts
Cause: Unknown
Error: No runner available for operation type [index-statrs]
```
#715 
`make test`
---

add improved error messaging in Worker class

---

.github/workflows/docker-build.yml

There's a conflict that happens when ARM64 Docker image is built. Started to randomly happen as of this 2/18/2025. 
Issue is a segfault issue that occurs when installing Qemu. Seems to be specific to how Qemu is installed and interacts with Docker and Ubuntu 20.04.
This is a temporary workaround to allow PRs to merge in. 
https://github.com/opensearch-project/opensearch-benchmark/issues/755
- Ran Dockerfile on Ubuntu 20.04
- Ran with Github Actions Workflow https://github.com/IanHoang/opensearch-benchmark/actions/runs/13461950670/job/37619149746
--- …

Update Docker-build Workflow to Address Segfault Issue 

---

.github/workflows/docker-build.yml

A recent kernel update randomized memory layout, resulting in a latent QEMU bug getting manifested, thereby causing the cross-platform ARM build to crash during `ldconfig` processing.  An older version of QEMU handles this case better, so reverting to it for now.
#755 
Verified the Docker build GitHub workflow completes successfully.
---

Interim workaround for QEMU bug that causes the Docker ARM build to fail

---

.github/workflows/docker-build.yml

Reverts opensearch-project/opensearch-benchmark#756 since #757 is a better long term solution.

Revert "Update Docker-build Workflow to Address Segfault Issue "

---

osbenchmark/benchmark.py
osbenchmark/worker_coordinator/worker_coordinator.py
tests/worker_coordinator/worker_coordinator_test.py

Adds a new `--load-test-qps` parameter for OSB. This parameter, when used with an appropriate test procedure such as:
```
{
"name": "timed-mode-test-procedure",
"schedule": [
{
"operation": "range",
"warmup-time-period": {{ warmup_time | default(300) | tojson }},
"ramp-up-time-period": {{ ramp_up_time | default(100) | tojson }},
"time-period": {{ time_period | default(300) | tojson }},
"target-throughput": {{ target_throughput | default(20) | tojson }},
"clients": {{ search_clients | default(20) }}
}
]
}
```
Overrides the target-throughput and client parameters, setting them to the integer value passed in by the user. 
OSB then uses the ramp-up property introduced in #725 to ramp up the number of clients over time until the target QPS is hit.
Example command:
`opensearch-benchmark …

Add `load-test-qps` parameter for dynamic client ramp up

---

.github/workflows/docker-push-release.yml

Enable write permissions for the `id_token` field to be able to create a JWT and acquire credentials successfully.
#717
---

Set GitHub ID token to be able to acquire credentials for the Docker build

---

.github/workflows/docker-push-release.yml

Use correct repo:tag specification for push to Docker Hub.
#717 
---

Fix repo specification for push to Docker Hub

---

.github/workflows/docker-push-release.yml

Skip running the Docker release workflow in forks of the authoritative repository.
#303 
---

Skip running the Docker release workflow in forks of the authoritative repository

---

setup.py

Change Topic name used by PyPI back to Benchmark from OSB
#768
---

Change Topic name used by PyPI back to Benchmark from OSB (#768)

---

osbenchmark/benchmark.py

Adds a warning when benchmarking multiple target hosts. Because OSB considers node count when checking for cluster health, two single-node clusters passed in via comma separated strings in the `--target-hosts` flag will result in an unhealthy status, and the benchmark will hang. However, as @IanHoang pointed out, passing in the two clusters via a JSON file will allow this check to pass. 
Here is an example of the warning:
```
dev-dsk-mikeovi-2b-40a6f422 % opensearch-benchmark execute-test --target-hosts=localhost:9200,localhost:3200 --workload=geonames --test-mode --kill-running-processes
/ __ \____  ___  ____ / ___/___  ____ ___________/ /_     / __ )___  ____  _____/ /_  ____ …
```

Add warning when benchmarking multiple target hosts

---

osbenchmark/worker_coordinator/runner.py
tests/worker_coordinator/runner_test.py

Add @time_func annotation to sleep runner's `__call__` method.
https://github.com/opensearch-project/opensearch-benchmark/issues/780 
Tested by adding sleep operation to a workload and it works as expected now
---

Add @time_func annotation to sleep runner

---

it/__init__.py

Update OpenSearch version used for integ tests to 2.17.
#776 
Ran integ tests.
---

Update OpenSearch version used for integ tests to 2.17

---

osbenchmark/workload/workload.py
tests/workload/params_test.py

It's been a while since OpenSearch [added](https://opensearch.org/docs/latest/im-plugin/index-codecs/) `qat_deflate` and `qat_lz4`  as additional index codecs, but they still weren't included here. This PR adds them.
No more "index.codec not found" error when `index.codec` is set to either `qat_deflate` or `qat_lz4`.
---

Add qat_deflate and qat_lz4 as additional index codecs.

---

DEVELOPER_GUIDE.md

Updated the developer guide with new Java requirements.
#776 
---

Updated the developer guide with new Java requirements

---

RELEASE_GUIDE.md
TRIAGE.md

Update release guide to reflect process for releasing from a branch.
---

Update release guide to reflect process for releasing from a branch

---

osbenchmark/benchmark.py
osbenchmark/workload_generator/config.py
osbenchmark/workload_generator/extractors.py
osbenchmark/workload_generator/helpers.py
osbenchmark/workload_generator/workload_generator.py
setup.py

OSB's Create-Workload feature is used to extract large volumes of documents from an index. Many users want to be able to extract a fraction of documents from throughout the index.  This PR allows users to do this. 
```
--sample-frequency="example_index:2"
```
If the index contains 5,000,000 documents, the above parameter would sample every other document and the resulting workload corpora will contain 2,500,000 documents.
These are rudimentary changes. Plan to evolve this feature eventually. A separate flag could be introduced later to randomly sample the index instead of specifying a sample frequency. 
https://github.com/opensearch-project/opensearch-benchmark/issues/395
Performed end-to-end testing on a large scale workload with indices. 
---
By submitting this pull request, I confirm …

Add Sample Frequency to Create-Workload

---

setup.py

Pypi release is blocked by the following error in Jenkins:
```
[31mERROR   [0m InvalidDistribution: Metadata is missing required fields: Name,        
Version.                                                               
Make sure the distribution includes the files where those fields are   
specified, and is using a supported Metadata-Version: 1.0, 1.1, 1.2,   
2.0, 2.1, 2.2, 2.3.       
```
Applying this short-term solution: https://github.com/pypi/warehouse/issues/15611#issuecomment-2793628089
---
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CO …

Bump twine version

---

.github/workflows/publish-release.yml

OSB needs to onboard to use Github Actions to release to PyPI. Changes in this PR are related to this effort. 
#451 
---

Onboard OSB to use GHA for PyPi Release

---

osbenchmark/worker_coordinator/worker_coordinator.py

An extra print statement was left in when merging [this PR](https://github.com/opensearch-project/opensearch-benchmark/pull/793#issue-2933104436).
Also fixes a bug where the feedback actor would continue scaling down clients by 100% after workers reach a joinpoint. The intended behavior is to scale down 100% of clients once the joinpoint is reached, then continue with the regular scale down percentage.
---
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#develop …

remove extra print statement

---

osbenchmark/worker_coordinator/runner.py
osbenchmark/workload/workload.py

This PR adds operations for remote model supports. Currently OSB only supports [pretrained models](https://docs.opensearch.org/docs/latest/ml-commons-plugin/pretrained-models/). If we want to add workloads that require using some models that not in the pretrained model list, we had to use remote models. In order to use these remote models, we need to create ML connectors and using the connector id to register the model. See instruction [here](https://docs.opensearch.org/docs/latest/ml-commons-plugin/remote-models/index/).
In this PR, we are adding three operations: CreateMlConnector, DeleteMlConnector and RegisterRemoteMlModel so that we can use remote models
---
By submitting this pull request, I confirm that my …

Add operations for create/delete ml connector and register remote model

---

osbenchmark/benchmark.py
osbenchmark/worker_coordinator/worker_coordinator.py

Adds CLI arguments related to redline testing. These include:
`--redline-scale-step`: controls how many clients to unpause per scaling iteration
`--redline-scaledown-percentage`: controls what percentage of clients to pause when an error occurs
`--redline-post-scaledown-sleep`: controls how many seconds the feedback actor waits before scaling up again after a scale down
`--redline-max-clients`: controls the max number of clients to allow during redline testing. If this one is unset, OSB will default to the number of clients defined in the test procedure
An example test run could look like:
```
opensearch-benchmark execute-test --pipeline=benchmark-only --target-hosts=localhost:9200 --workload-path=big5 --test-procedure=timed-mode-test-procedure --kill-running-processes --redline-test …
```

Add configurable values for redline testing

---

osbenchmark/benchmark.py

There's a bug in `--redline-scaledown-percentage` parameter option. Argparse thinks the help text needs to be formatted because there's a single `%` character. To tell Argparse to display the character, we need two of them.
#855 
Tested with and without the change. Output shows up now when the change is present.
```
--redline-scaledown-percentage REDLINE_SCALEDOWN_PERCENTAGE
What percentage of clients to remove when errors occur (default: 10%).
```
---

Fix help text bug for execute-test subcommand

---

osbenchmark/benchmark.py
osbenchmark/exceptions.py
osbenchmark/resources/example-basic-mappings.json
osbenchmark/resources/example-complex-mappings.json
osbenchmark/resources/sdg-config.yml
osbenchmark/synthetic_data_generator/__init__.py
osbenchmark/synthetic_data_generator/custom_synthetic_data_generator.py
osbenchmark/synthetic_data_generator/helpers.py
osbenchmark/synthetic_data_generator/input_processor.py
osbenchmark/synthetic_data_generator/mapping_synthetic_data_generator.py
osbenchmark/synthetic_data_generator/synthetic_data_generator.py
osbenchmark/synthetic_data_generator/types.py
setup.py
tests/synthetic_data_generator/custom_synthetic_data_generator_test.py
tests/synthetic_data_generator/mapping_synthetic_data_generator_test.py

Cherry-picked commit to `2.0.0-develop` branch. 
This PR was already approved in #829 PR and confirmed they have the same number of changes
---

Add Synthetic Data Generation in OSB (#829)

---

osbenchmark/worker_coordinator/worker_coordinator.py
tests/worker_coordinator/worker_coordinator_test.py

Changes a few items related to redline testing:
- Change if/else statements in `handle_state` of the feedback actor so the proper choices are made depending on Actor state
- Removes logic to scale clients down to 0 once a joinpoint is hit
- Adds an 'error threshold', FeedbackActor treats this as a ceiling during redline testing so it does not recklessly scale past this ceiling
- Adds logic to probe past the ceiling during testing: Every interval, if we're at the ceiling, there is a small chance of adding an extra client to probe past it. After 10 intervals, an extra client is added by default. This results in a more careful scale up and more precise max client count
- Request handling in the `AsyncExecutor` class has been abstracted into two separate functions, `handle_redline` and …

Updates to Redline Testing

---

osbenchmark/benchmark.py
osbenchmark/metrics.py
osbenchmark/worker_coordinator/worker_coordinator.py
tests/worker_coordinator/worker_coordinator_test.py

Introduces CPU-based feedback for redline testing.
Requires the user to have a metrics store, as well as enabling the node-stats telemetry devices.
The lack of either results in test failure:
```
[ERROR] Cannot execute-test. Error in worker_coordinator (CPU-based feedback requires a metrics store. You are using an in-memory metrics store)
```
And
```
[ERROR] Cannot execute-test. Error in worker_coordinator (Node stats not enabled. You must use `--telemetry node-stats` flag for CPU-based feedback)
```
Also requires the use of the `--redline-cpu-max-usage` flag. This flag takes an int and determines the max threshold for the CPU load of any given node during the test.
Additional flags that are not required, include:
`--redline-cpu-window-seconds` - Controls the size of the window from which …

Introduce CPU-based Feedback for Redline Testing

---

osbenchmark/benchmark.py
osbenchmark/worker_coordinator/worker_coordinator.py

lack of `mandatory=False` flag when fetching cpu_max value from config object would cause normal benchmarks to crash with the following:
```
(.venv) [ec2-user@ip-123-45-67-890 opensearch-benchmark]$ osb execute-test --workload=big5 --target-host="localhost:9200" --workload-params="number_of_replicas:0" --exclude-tasks="type:search" --user-tag="version:osb-2"
/ /_/ / /_/ /  __/ / / /__/ /  __/ /_/ / /  / /__/ / / /  / /_/ /  __/ / / / /__/ / / / / / / / / /_/ …
```

add mandatory=False flag for CPU feedback fetch

---

osbenchmark/worker_coordinator/worker_coordinator.py
tests/worker_coordinator/worker_coordinator_test.py

Improved Readability and Maintainability of AsyncExecutor's `__call__` Method
The following private helper methods have been introduced to encapsulate distinct parts of the original logic:
*   **`async def _wait_for_rampup(self, rampup_wait_time)`**:
*   Handles the logic for waiting during the ramp-up phase.
*   **`def _handle_client_state(self, was_paused, client_state, total_start, expected_scheduled_time)`**:
*   Manages client state adjustments, particularly relevant for redline testing when clients might be paused or resumed.
*   **`async def _prepare_context_manager(self, params)`**:
*   Determines and prepares the correct context manager for the outgoing request. This includes specific handling for "produce-stream-message" operations (using `MessageProducerFactory`) and …

REFACTOR async def __call__(self, *args, **kwargs)

---

.github/workflows/unit-test.yml

adds if condition so lint checker only runs if the `2.x-terms-only` label is present
---

only run lint checker if 2.x-terms-only label is present

---

osbenchmark/metrics.py
osbenchmark/results_publisher.py
osbenchmark/worker_coordinator/runner.py
osbenchmark/worker_coordinator/worker_coordinator.py
osbenchmark/workload/params.py
tests/worker_coordinator/runner_test.py
tests/worker_coordinator/worker_coordinator_test.py

This is a high-level implementation of the issue linked below. Basically, a workload can specify query profile metrics and then the benchmarking tool samples the first N queries with a profiler. OSB then traverses through the entire profile tree and sums the profile metrics that were passed in (if present). The queries sampled for profiling are excluded from the operational metrics to avoid skewing the results. This means that a new sampler had to be created for the profile metric samples. Also, there are no checks currently on the sample size given because of how `schedule` is a generator type.
Ideally, it would be nice if samples could be added more easily to a `Sampler` (so we wouldn't have to define a new `Sample` subclass for every single metric we want to get percentiles from). It …

Adding query profiling metrics to metrics store

---

osbenchmark/cloud_provider/vendors/s3_data_producer.py
osbenchmark/data_streaming/data_producer.py
osbenchmark/exceptions.py
tests/data_streaming/__init__.py
tests/data_streaming/producer_test.py

Initial implementation of the Data Producer for data streaming with support for S3.  Scaling improvements will be added separately since multi-part download functionality needs to be explicitly managed.
#872 
```
After setting credentials appropriately and attempting to download a 10 GB corpus:
[926]osb-dst:SCR-0:test@$ time python3 -m osbenchmark.cloud_provider.vendors.s3_data_producer big5-corpus documents-10.json
real    1m10.78s
user    0m26.51s
sys     0m37.87s
[927]osb-dst:SCR-0:test@$ ls
total 10486168
51200 chunk-0000  51204 chunk-0016  51200 chunk-0032  51200 chunk-0048  51200 chunk-0064  51204 chunk-0080  51204 chunk-0096  51200 chunk-0112  51200 chunk-0128  51204 chunk-0144  51200 chunk-0160  51204 chunk-0176  51204 chunk-0192
51204 chunk-0001  51200 chunk-0017  51200 …
```

Data Producer with multi-part downloads and partitioning

---

osbenchmark/benchmark.py
osbenchmark/resources/benchmark.ini
osbenchmark/worker_coordinator/worker_coordinator.py

Adds a new `[redline]` section to `benchmark.ini` along with some default values for redline testing. These are equivalent to the default values originally used in the FeedbackActor, and allow the user to customize various parts of redline testing from the config object rather than using command flags.
The priority for which value to use is: 
command flag -> config object values -> default values in the `ConfigureFeedbackScaling` class.
And the values that can be customized in the config object include:
- The scale_step (how many clients are unpaused per tick)
- The scale_down_percentage (what percentage of clients are scaled down upon an error)
- The sleep_seconds (how long the FeedbackActor chooses to rest before pushing more load on the host)
- The cpu_window_seconds (How long of a …

add ability to use benchmark.ini file to customize redline tests

---

osbenchmark/worker_coordinator/runner.py

k-NN repo had changes dealing with KNNQuery and the simplification to its output (no more "_after_ann" or "_after_filter"). Therefore, the newly merged code dealing with profile metrics getting benchmarked needs to change. This is a simple if-statement removal. Changes shouldn't occur beyond this because users will just define all metrics they want via parameter file.
---

[BUG FIX] Profile Metric KNNQuery Fix

---

osbenchmark/client.py
osbenchmark/worker_coordinator/worker_coordinator.py
setup.py
tests/client_test.py
tests/worker_coordinator/worker_coordinator_test.py

This PR: 
* Fixes a bug where latest major version 3.0.0 of opensearch-py is getting installed that has breaking changes and failing OSB run. 
* Adds new `session` parameter for `amazon_aws_log_in` to use boto3 session credentials to auto-refresh before expiry. 
* Fixes a bug in AsyncExecutor class which was wrongly referring the client options from config object. 
---

auto-refresh aws creds using boto3

---

osbenchmark/__init__.py
osbenchmark/version.py

Adding a quick fix for removing pkg-resources
#867 
Ran unittests and synthetic data generator and confirmed that warning does not show up anymore. 
---

Address pkg_resources deprecation

---

osbenchmark/aggregator.py
osbenchmark/metrics.py

Fixes to aggregate command to prevent key errors + update function name for storing aggregated results
running aggregate command with changes applied
---

fixes for aggregate command

---

CREATE_WORKLOAD_GUIDE.md
DEVELOPER_GUIDE.md
PYTHON_SUPPORT_GUIDE.md
it/__init__.py
osbenchmark/benchmark.py
osbenchmark/workload_generator/workload_generator.py
samples/ccr/start.sh
scripts/expand-data-corpus.py

Address integration test failures
---

Address Integration Tests

---

osbenchmark/resources/cluster_configs/main/cluster_configs/v1/vanilla/templates/config/jvm.options
osbenchmark/utils/process.py

Fix integration test failure in 2.0 RC.
---

Fix integ test failure in 2.0 RC

---

DEVELOPER_GUIDE.md
PYTHON_SUPPORT_GUIDE.md

- Updates PYTHON_SUPPORT_GUIDE.md with example from @gkamat's PR for removing support for Python 3.8 and 3.9 and adding support for Python 3.10 and 3.11
- Updates DEVELOPER_GUIDE.md instructions for downloading Pyenv. This was used and confirmed with Amazon Linux 2023 when testing out changes for Python 3.10
---

Update PYTHON_SUPPORT_GUIDE.md and DEVELOPER_GUIDE.md
